Update building instructions for Windows
Stellarium/stellarium pull request #1444
Opened 2020-12-28 15:49 UTC by Thomas1664

### Description

Fixes #1443 

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?
I updated the building instructions for Windows for use with Visual Studio 2019 and Qt 5.15.2

**Test Configuration**:
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-12-28 15:57 UTC, alex-w requested changes
Please fix PATH variable

2020-12-28 16:22 UTC, gzotti commented
I would not delete the information applicable to MSVC2017. The changes are mostly trivial, but changed/missing URLs are a problem. Stellarium can still be built with Qt5.9. You can just use MSVC2017 and don't need to bother with upgrading. Further relevant bits of information are 

* the ANGLE library which should be taken from Qt5.6, all later versions don't work. (Don't ask us why. Find a solution!)  
* Qt5.15.0 and 5.15.1 have a buggy lconvert and should not be used. Also lconvert on Qt5.15.2 still allocates GBs of memory for translation of a few MBs of strings, if it can get it.

2020-12-28 17:22 UTC, gzotti commented on BUILDING.md
> -$ cmake -DCMAKE_INSTALL_PREFIX=c:\stellarium-bin -G "Visual Studio 15 2017 Win64" ../..
Show both lines! Who would know "Win64" has to be added for 2017?

2020-12-29 05:32 UTC, alex-w commented
the ANGLE library from Qt 5.6 may be obtained from https://github.com/Stellarium/stellarium-data/releases/download/qt-5.6/libGLES-x64.zip or https://github.com/Stellarium/stellarium-data/releases/download/qt-5.6/libGLES-Win32.zip

2020-12-30 09:15 UTC, alex-w approved these changes
Looks OK, @gzotti?

2020-12-30 10:46 UTC, gzotti approved these changes
Fine for me.

2020-12-30 10:58 UTC, merged