WIP: Switch from Bortle class to luminance as the quantity of light pollution
Stellarium/stellarium pull request #1723
Opened 2021-06-06 18:11 UTC by 10110111

This PR addresses #1586.

### WIP

This PR is not complete, but I'd like to get some feedback on it before I proceed. What's planned but not yet done is:

* GUI as proposed in https://github.com/Stellarium/stellarium/issues/1586#issuecomment-813623246 (currently it's just a 7-digit `QDoubleSpinbox`)
* User Guide should reflect the change in the interface, particularly for the Landscape config files.

### Description

Bortle scale has several disadvantages:

1. It was designed as a guide for humans, not input for machines. From this follows the next disadvantage.
2. It's discrete: each point on the scale corresponds to a range of NELM values, which makes it imprecise a program's input.
3. It's subjective: based on naked-eye limiting magnitude that depends on observer's visual acuity.
4. It isn't as widely used (and thus validated) as photometric units.

OTOH, luminance is the quantity that defines all the relevant effects of light pollution.

This commit makes luminance in cd/m² the input parameter, leaving for backwards compatibility the option of supplying Bortle class in Landscapes. Some changes to calculations had to be introduced, as listed below.

1. `StelSkyDrawer::getNELMFromBortleScale` was reimplemented in `StelCore::bortleScaleIndexToNELM` using a bit different representative values of NELM - to simplify the comment documenting the choice. The values are almost the same: each old value except one will be reproduced by adding 0.05 to the new ones.
2. Calculation of `B_mpsas` in `Nebula.cpp` was trying to convert from Bortle class to magnitude scale using some formula from Schaefer paper, the same paper as I used in `StelCore::luminanceToNELM`, but without explaining the steps to get the formula. The old expression form `Nebula.cpp` (which is widespread over the Internet) doesn't work near NELM==8 (see the discussion at https://astronomy.stackexchange.com/q/43313), while the one I used does. Anyway, `Nebula`'s logic is tied to luminance, so if the user supplies luminance instead of Bortle class, it'll be as intended.

For some reason, stars/init_bortle_scale setting defaulted to 3 while StelLocation::DEFAULT_BORTLE_SCALE_INDEX is 2. I've retained these preferences.

Technical note: I had to use `QVariant` instead of an `optional` type because Stellarium isn't using C++≥17 (C++17 has `std::optional`), nor anything from Boost (which has `boost::optional`). The other alternative was to make my own `optional`, but that seemed like overkill.

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

## Checklist:
- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-06-06 18:22 UTC, alex-w requested changes
I see in the log:
```
QObject::connect: No such slot StelSkyDrawer::setBortleScaleIndex(int)
QObject::connect:  (receiver name: 'StelSkyDrawer')
```

Please change the default step for luminance input box

2021-06-06 18:32 UTC, 10110111 commented
> I see in the log:

Hmm, where could it come from?.. I don't have any such in the log. I don't even find anything like `connect.*setBortleScaleIndex` int the sources...

> Please change the default step for luminance input box

What could a good step value be?

2021-06-06 19:27 UTC, gzotti commented
That's a tricky GUI issue. The Bortle scale may offer itself as human-readable and easier to remember/estimate external representation of luminance values which may not be as intuitive. I cannot say whether more users are used to discussing finding a "class 3 sky" than "XY cd/m²". Others in my vicinity are rather discussing their NELM directly. So, it may be good to use cd/m² inside the program, but keep the Bortle scale as GUI manipulator, and add a table of values to the User Guide. Maybe we can use graduations in tenths of "Bortle Units" for finer adjustments? Or even alternatives, i.e. offering one both interfaces, configurable. Or a slider which moves cd/m² but in addition shows Bortle values.

2021-06-06 19:39 UTC, 10110111 commented
> So, it may be good to use cd/m² inside the program, but keep the Bortle scale as GUI manipulator

Yeah, this is the next step. As I said above all, this is not yet done. The main point of the current RFC is about the infrastructure changes. The final more complex GUI will just use the infrastructure developed here.

2021-06-07 03:08 UTC, alex-w commented
> > Please change the default step for luminance input box
> 
> What could a good step value be?

I think it should be reduced to the first significant digit

2021-06-07 07:51 UTC, gzotti commented
Not sure (sorry, did not read into this topic for some years now). Should this not be logarithmic?

2021-06-07 07:55 UTC, 10110111 commented
> Not sure (sorry, did not read into this topic for some years now). Should this not be logarithmic?

It should, but spinboxes are limited in their behavior. Once again, the current version is minimal, it's meant to just show that the infrastructure changes don't break _functionality_. The UI part is irrelevant here.

Well, if no one here is willing to review the "invisible" side, I guess I should close this PR and come back when the final GUI is ready. I just didn't want to rework everything if the infrastructure appears to be unsatisfactory.

2021-06-07 11:43 UTC, gzotti commented
Sorry, not really unwilling, but too occupied with "real" work these weeks. Really sorry, I still must review your other PR which looks visually suspiciously bad to me. 
You can continue development in this PR and set it from grey draft to green "merge candidate" (I don't see the correct word now...). I doubt I will be able to touch this part of the code in June.

2021-06-11 11:48 UTC, alex-w commented
> What could a good step value be?

Is this question actual still?

2021-06-11 11:51 UTC, 10110111 commented
> Is this question actual still?

No, and it wasn't from the beginning. I was trying to remove distractions and make actual review possible. But now I'm not sure this PR makes any sense.

2021-06-11 11:51 UTC, closed without merging

2021-06-11 14:25 UTC, 10110111 commented
Subsequent development of this issue is in [10110111:light-pollution-gui](https://github.com/10110111/stellarium/commits/light-pollution-gui) branch. I'll open a PR when I consider it ready.