Introducing new western sky culture sternenkarten.com
Stellarium/stellarium pull request #1862
Opened 2021-09-02 19:56 UTC by seescho

### Description
Introduce the new western sky culture sternenkarten.com

### Screenshots (if appropriate):

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### How Has This Been Tested?
Compiling, installing and testing on openSUSE Tumbleweed.
**Test Configuration**:
* Operating system: openSUSE Tumbleweed
* Graphics Card: Intel-chipset graphics

## Checklist:

- [x ] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-09-03 01:46 UTC, alex-w requested changes
I see `star_names.fab` has references, but file `references.fab` is missing

2021-09-03 04:05 UTC, alex-w commented on skycultures/western_sternenkarten/info.ini
> +boundaries = iau
Please add license info here, for example: `license = CC BY-ND 4.0 International`

2021-09-03 14:24 UTC, alex-w commented
Please check items from QA checklist also

2021-09-03 14:28 UTC, alex-w approved these changes

2021-09-03 15:05 UTC, seescho commented
> Please check items from QA checklist also

done

2021-09-04 07:00 UTC, alex-w approved these changes
Thank you!

2021-09-04 07:00 UTC, merged