Add Solar Eclipses to Astronomical calculations
Stellarium/stellarium pull request #2218
Opened 2022-01-29 12:41 UTC by worachate001

### Description
This PR will fix issue #407 by adding the method to search for all solar eclipses during user-input timespan.

The calculations are divided into two tabs.

First tab for generic information of all solar eclipses:
* Date and time of greatest eclipse.
* Saros
* Type of eclipses
* Gamma
* Magnitude at greatest eclipse
* Geographic coordinates of greatest eclipse
* Altitude of the Sun at greatest eclipse
* Path Width of umbra/antumbra
* Central duration of totality/annularity
* Double click the event will go the the location and time of greatest eclipse (need help to handle it properly when location changed)

Second tab for information of solar eclipses visible at current location
* Date of eclipse
* Time of each contacts and maximum eclipse
* Magnitude of maximum eclipse
* Duration of totality/annularity if the eclipse is total/annular
* Double click the event will go the time of maximum eclipse

Note:
* I'm still testing the tool with many situations to search for possible bug.
* Lunar eclipse calculations are also improved by removing unnecessary steps.

### Screenshots (if appropriate):

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x ] This change requires a documentation update

### How Has This Been Tested?

**Test Configuration**:
* Operating system: Ubuntu 20.04
* Graphics Card: NVidia Geforce RTX

## Checklist:

- [x ] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-01-29 13:17 UTC, alex-w requested changes
Thanks for adding new features!

I see problem: in the tab "All Solar Eclipses" after double click the info about location is not changes - this is wrong!

2022-01-29 13:19 UTC, worachate001 commented
> Thanks for adding new features!
> 
> I see problem: in the tab "All Solar Eclipses" after double click the info about location is not changes - this is wrong!

Yes, I need your help about that. The location changed, but not the info.

2022-01-29 13:42 UTC, alex-w commented
> Yes, I need your help about that. The location changed, but not the info.

In _AstroCalcDialog::selectCurrentSolarEclipse_:

```
StelLocation loc = core->getCurrentLocation();
loc.latitude = lat;
loc.longitude = lon;
loc.altitude = 10; // 10 meters above sea level
loc.name = ""; // Or some good name
core->moveObserverTo(loc, 0.);

if (objectMgr->findAndSelect(name)) // "name" has English only name
```

2022-01-29 13:50 UTC, alex-w commented
I guess the first column (Date and Time) should be in UTC for tab "All Solar Eclipses". @gzotti?

2022-01-29 14:09 UTC, gzotti commented
I am in a workshop and cannot look at it closely. My natural feeling is it should be user time zone. But I don't see the GUI context now. Can answer in 6 hours.

2022-01-29 14:14 UTC, alex-w commented on src/gui/AstroCalcDialog.cpp
> +					if ((s + nc * 223 - 1) < 0)saros -= 223;
Missing space?

2022-01-29 14:15 UTC, alex-w commented
> I am in a workshop and cannot look at it closely. My natural feeling is it should be user time zone. But I don't see the GUI context now. Can answer in 6 hours.

So, it shgould be as is - thanks!

2022-01-29 14:34 UTC, worachate001 commented on src/gui/AstroCalcDialog.cpp
> +					if ((s + nc * 223 - 1) < 0)saros -= 223;
Thank you, fix on the way.

2022-01-29 14:44 UTC, alex-w commented
I have question for “Altitude” column - probably this data calculated due it presented on NASA eclipses website - why it rounded to whole?

2022-01-29 14:54 UTC, worachate001 commented
> I have question for “Altitude” column - probably this data calculated due it presented on NASA eclipses website - why it rounded to whole?

It's altitude with no refraction, so they are not very accurate. Altitude is useful because you will know that the Sun is high or low above the horizon during the eclipse.

2022-01-29 15:03 UTC, alex-w commented
I'm afraid that in _selectCurrentSolarEclipse_ there should be something like:

```
StelLocation loc;
loc.latitude = lat;
loc.longitude = lon;
loc.altitude = 10; // 10 meters above sea level
loc.name = q_(“Greatest eclipse’s point”);
loc.planetName = "Earth”;
loc.ianaTimeZone = “LMST”;
core->moveobserver(location, 0.);
```

2022-01-29 15:05 UTC, worachate001 commented
I will note that in some dates, especially annular eclipse with short duration, you can see that there is a little difference between position of the Moon and Sun at the place of greatest eclipse. I'm still looking for the reason behind it (maybe about the Besselian elements).

2022-01-29 15:06 UTC, alex-w commented
Maybe column “Saros Number” should be identical for all subtabs and just “Saros”?

2022-01-29 15:07 UTC, worachate001 commented
> Maybe column “Saros Number” should be identical for all subtabs and just “Saros”?

I agree, thinking about that too.

2022-01-29 15:09 UTC, alex-w commented
Please add translatable tooltips for data in columns

2022-01-29 16:28 UTC, worachate001 commented
> Please add translatable tooltips for data in columns

Thank you for suggestion, I'm adding some of them

2022-01-29 18:10 UTC, alex-w commented
Maybe synchronize dates in the input fields for Solar eclipses will good idea, e.g. if user changes the startup date for tab "All Solar Eclipses", then set it as a startup date in the tab "Local Solar Eclipses" also?

@gzotti?

2022-01-29 18:11 UTC, alex-w approved these changes

2022-01-29 20:55 UTC, gzotti commented
Great addition, thank you! However, I really want to also have good documentation of our sources. Presumably you did not invent the way of computing from scratch, right? Did you use some algorithm that is available in the literature? Please follow usual standards, at least author, book title, publisher and year. And ISBN/DOI or URL for a modern source where available.

2022-01-30 02:12 UTC, alex-w commented on src/gui/AstroCalcDialog.cpp
> +									eclipseTypeStr = "Partial";
Please fix translatability

Hint: `qc_("Partial", "eclipse type");`

2022-01-30 02:12 UTC, alex-w commented on src/gui/AstroCalcDialog.cpp
> +									eclipseTypeStr = "Annular";
Please fix translatability

Hint: `qc_("Annular", "eclipse type");`

2022-01-30 02:12 UTC, alex-w commented on src/gui/AstroCalcDialog.cpp
> +									eclipseTypeStr = "Total";
Please fix translatability

Hint: `qc_("Total", "eclipse type");`

2022-01-30 07:34 UTC, alex-w approved these changes
Thanks!

2022-01-30 07:36 UTC, merged