Added support directional elongation
Stellarium/stellarium pull request #2405
Opened 2022-04-17 17:07 UTC by alex-w

### Description
Added option to switch between directional and nondirectional ecliptic elongation. See discussion #2368 for details.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-04-17 18:36 UTC, gzotti requested changes
For me it can be even simpler, no flag, config etc. Just write E/W instead of +/-. 

However, I just see that in the InfoMap the signed &Delta;&lambda; is missing. I think there a signed number is more useful (let the user of the data decide what to do). 

Given that the other (purely angular) elongation is always positive, can we write it without the plus sign?

2022-04-17 23:51 UTC, alex-w commented
> For me it can be even simpler, no flag, config etc. Just write E/W instead of +/-. But extra flag is OK if you prefer.

Now it uses E/W instead of +/-

> However, I just see that in the InfoMap the signed Δλ is missing. I think there a signed number is more useful (let the user of the data decide what to do).

Added, on Earth only

> Given that the other (purely angular) elongation is always positive, can we write it without the plus sign?

OK, but it some hackish

2022-04-18 09:47 UTC, gzotti commented on src/core/modules/Planet.cpp
> +		StelUtils::radToDecDeg(elongAlongEcliptic, sign, elongationDecDeg);
The function radToDecDeg is IMHO unneeded, and I remove its use it whereever I see it. Why dissect sign into a separate variable just to apply it immediately after once and never again? Just say 

elongationDecDeg=fmod(elongAlongEcliptic*M_180_PI, 360.); 

We have this (what feels like) thousands of times in our code. 

I will push a commit with some other changes I see useful.

2022-04-18 11:57 UTC, gzotti commented on src/core/modules/Planet.hpp
> +	//! - modern-elongation (elongation in ecliptic longitude or Δλ; on Earth only; radians)
I fixed the "modern" name use (changed to ecl-elongation), because it is actually the more classical use.

2022-04-18 11:58 UTC, gzotti approved these changes
Else it's fine for me now.

2022-04-18 11:59 UTC, alex-w commented
> Else it's fine for me now.

Please merge it

2022-04-18 12:02 UTC, merged