Quick way to jump to the solstice/equinox
Stellarium/stellarium pull request #2497
Opened 2022-06-27 13:35 UTC by alex-w

### Description
This pull request contain the code for compute the time of equinoxes and solstices and set of actions to jump to the solstice/equinox at current, next or previous year. The default hotkeys for actions are not defined.

Fixes #1394 (issue)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-06-28 06:07 UTC, alex-w commented
@gzotti please review this PR

P.S. I guess we can add new groups of actions - Special date and time - for equinoxes/solstices and RTS/twilight. What you think about it? Mabe with extract all related code into separate class.

2022-06-28 06:11 UTC, Atque commented
I see this only has hotkeys that can be assigned. Would it be possible to add a windows or something (perhaps an extra tab in the Date/Time menu?), so the user won't have to use designated keys?

2022-06-28 06:18 UTC, alex-w commented
Maybe later, I have some ideas for it. 

P.S. Thank you very much for the screenshot

2022-06-28 08:44 UTC, Atque commented
Hm, yes, that might be the most sane place for it.

2022-06-29 14:47 UTC, gzotti requested changes
I see several problems: 
(1) You are always computing all 4 dates and then use just one. This is usually not a problem with today's fast PCs, but a principal waste of computing. 
(2) Add source! This is from Astronomical Algorithms (2nd ed.), ch.27. 
(3) It is only for -1000...+3000 and delivers 0 or does nothing outside those dates. Most users only interested in their own lifetimes will not notice. However, a more general approach should find 0/90/180/270 from ecliptical longitudes in our own algorithms, be it VSOP or DE*. The Calendars plugin has such a function. Calendar::solarLongitudeAfter(). It also uses its private version of solar longitude, to stick to its source book, but this and related functions could be used for a more general solution.  For now, you can add these functional deficiencies as code and SUG comments, and add into the Doxygen a @todo note that we don't forget to improve this function later. Or we try to solve it now for good.

2022-06-30 03:56 UTC, alex-w commented
Hmm... The (3) can be not a fast to resolve, so, let me postpone this PR to version 0.22.3

2022-07-14 14:08 UTC, alex-w commented
This PR was superseded by the [specific-time](https://github.com/Stellarium/stellarium/tree/refactoring/specific-time) branch

2022-07-14 14:08 UTC, closed without merging