Observing lists fix
Stellarium/stellarium pull request #2553
Opened 2022-08-04 15:48 UTC by Jocelyn1109

2022-08-09 13:50 UTC, alex-w commented
@Jocelyn1109 please use QRegularExpression

2022-08-16 18:03 UTC, alex-w requested changes
In the editor of list I see 2 checkboxes - Ra & Dec - why not use just one - Coordinates?

The Name column - I think objects without names should contain "dash" char.

The Magnitude column: please use formatted output (2 digits after dot for all magnitudes + "dash" char for magnitudes over 98 - because magnitude 99 used for objects without magnitudes).

P.S. See AstroCalc tools for obtain examples for use "dash" char and formatting output of magnitudes

2022-08-17 10:51 UTC, Jocelyn1109 commented
@alex-w  "In the editor of list I see 2 checkboxes - Ra & Dec - why not use just one - Coordinates?" -> yes, we can use ony one checkbox for both if you want. I thought they should be separated.

2022-09-08 01:25 UTC, alex-w commented
@Jocelyn1109 please mark which issues this pull request should closes (via edit description of pull request)

2022-09-09 20:11 UTC, alex-w commented
I see no fixes for Name and Magnitude columns...

2022-09-09 20:17 UTC, Jocelyn1109 commented
I forgot I will aff the fix this week-end. Sorry

Envoyé depuis Yahoo Mail pour Android 
 
  Le ven., sept. 9, 2022 à 22:12, Alexander V. ***@***.***> a écrit:   


I see no fixes for Name and Magnitude columns...

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-09-10 10:18 UTC, Jocelyn1109 commented
@alex-w  for the empty name, do you speak about "nameI18n" ?

2022-09-10 10:29 UTC, alex-w commented
> @alex-w for the empty name, do you speak about "nameI18n" ?

Yes, see selected line on the screenshot

![stellarium-018](https://user-images.githubusercontent.com/88731/189479332-c9511147-15f2-4cb8-8bb5-82d052f6d5dd.jpg)

2022-09-10 10:32 UTC, Jocelyn1109 commented
> 

and for magnitude it is like that:
`magnitude > 98.f ? dash : QString::number(magnitude, 'f', 2)));`

2022-09-12 02:24 UTC, alex-w approved these changes

2022-09-12 02:25 UTC, alex-w commented
I think the changes in the code is ready to public testing

2022-09-12 14:26 UTC, gzotti commented
I have a few entries for the Moon, stored with date/location. In the bookmark list, all show the coordinates of the "current" moon. Would it not be better to store&retrieve also coordinates, or at least recreate the coordinates from the stored time&locations?

When a bookmark was stored, it apparently stored the location name, but no other data. Sometimes this location comes from a "landscape". On bookmark loading, users are thrown to long/lat 0/0. If location was not found, it is better to not move to the ocean around the equator. 

On the plus side, I have so far not triggered a crash :-)

2022-09-12 14:33 UTC, Jocelyn1109 commented
Hi, @gzotti is it possible to have your observinglist.json ?
I would like to analyze and understand what you want .  :)

Many thanks.

Jocelyn

2022-09-12 15:17 UTC, gzotti commented
OK, here. (Renamed for Github)

[observingList.json.txt](https://github.com/Stellarium/stellarium/files/9549304/observingList.json.txt)

I see when location is empty, the user is moved to 0/0. It would be better to not move location in this case. Probably also locations only retrieved from the landscapes are lost on storing when there is no coordinates for the Landscape placename stored in the location database. It may be useful to explore storing the whole location (name, coordinates, timezone, LP info, ...) into a string which could be retrieved by Location::createFromLine(). For this, developing a fitting Location::toString() would be required. In any case, if no numerical data can be found for a location, the position should not change to just 0/0. (Note somebody may store 0/0 explicitly! Then it is required to go there...)

2022-09-13 09:14 UTC, gzotti commented
Of course StelLocation::serializeToLine() is the inverse of createFromLine() which you can use to encode all location data into a single entry for the JSON.

2022-09-13 10:43 UTC, Jocelyn1109 commented
@gzotti 
"I have a few entries for the Moon, stored with date/location. In the bookmark list, all show the coordinates of the "current" moon. Would it not be better to store&retrieve also coordinates, or at least recreate the coordinates from the stored time&locations?" -> yes it is absolutely better and I will modify this point :)

2022-09-19 11:32 UTC, gzotti commented
Yes, this is good. Imagine you want to show the eclipsed Moon from various locations at the same time. This should allow demonstrating that it appears equally dark, but in different places (az/alt) in the sky, and esp. in slightly differing places depending on topographic parallax.

As said, please also consider optionally storing the landscape ID for an automated context change.

2022-09-19 11:43 UTC, Jocelyn1109 commented
@gzotti 
the landscape id is already taken into account but optional (checkbox in create dialog).

```
"observingLists": {
        "{4c48abf7-8ea3-4b06-be90-dc7655b5e2d0}": {
            "creation date": "2022-08-08 07:00:45",
            "description": "location tests",
            "landscape id": "",
            "name": "location test",
            "objects": [
                {
                    "constellation": "CMa",
                    "dec": "-26°23'26\"",
                    "designation": "HIP 34444",
                    "fov": 60,
                    "isVisibleMarker": false,
                    "jd": 2459799.948451157,
                    "location": "Tamiyah, Northern Africa",
                    "magnitude": "1.8",
                    "nameI18n": "Wezen",
                    "objtype": "double star",
                    "ra": "7h08m22.2s",
                    "type": "Star"
                },
            ],
            "sorting": ""
        },
```

2022-09-20 08:43 UTC, alex-w commented
@Jocelyn1109 is it possible pushing the fixes in next 2 days to adding them into RC1?

2022-09-20 08:48 UTC, Jocelyn1109 commented
@alex-w yes I will do my best :)

2022-09-21 13:17 UTC, alex-w commented
@gzotti is the currently state of the pull request enough to merge and extract the translatable lines to prepare RC1 tomorrow?

2022-09-21 13:28 UTC, Jocelyn1109 commented
@alex-w @gzotti 
Tonight I will push the code that fixes a SIGSEV.
But for the moment the problem of Georg is not corrected because I do not yet know how to retrieve the coordinates (Ra and Dec) of an object with the time and the location.

2022-09-21 14:11 UTC, gzotti commented
> @alex-w @gzotti Tonight I will push the code that fixes a SIGSEV. But for the moment the problem of Georg is not corrected because I do not yet know how to retrieve the coordinates (Ra and Dec) of an object with the time and the location.

If this is a problem only for the old bookmark lists, don't bother.  For new entries it should be enough to store Ra/Dec when the entry is created with timestamp. But it is important to not change location if the location cannot be decoded correctly. 

Hmm, location should as discussed be stored as StelLocation::serializeToLine() and decoded with StelLocation::createFromLine(const QString& line); to fully store data in case location comes from a landscape or was manually configured.

The GUI should be edited a bit: move all optionally stored items above or below. Currently checkboxes in the list edit panel to store coordinates and fov are below, landscape is above, and there is no JD entry.  In the data retrieval panel, there are only checkboxes for JD and location, no landscapes and no fov. 

Please also rebase this branch from current master.

2022-09-21 14:13 UTC, gzotti commented on stellarium.kdev4
> +[Project]
I think this file should be removed from the repository.

2022-09-22 10:34 UTC, merged