Add support for OpenGL 3.3 Core profile
Stellarium/stellarium pull request #2729
Opened 2022-10-07 00:28 UTC by 10110111

### Description

This set of changes should make it possible to run Stellarium with ShowMySky model on macOS and other systems where Compatibility profile is not supported.
Core profile is now made the default, an option is added to request compatibility profile: `--opengl-compat`.

Fixes #2707 

@alex-w Please test it on macOS and tell me if you find problems. They may appear anywhere: in ShowMySky, in rendering of various objects (planets, stars, nebulae, ground, etc.).
@gzotti Please test it on the minor systems that are not capable of OpenGL 3.3. It may work, but it also might fail if the systems don't support VAO.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the [code style](http://stellarium.org/doc/head/codingStyle.html) of this project.
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (header file)
- [ ] I have updated the respective chapter in the Stellarium User Guide
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-10-07 03:17 UTC, alex-w requested changes
The running Stellarium is fails on macOS due incompatible shaders
[log.txt](https://github.com/Stellarium/stellarium/files/9730433/log.txt)

2022-10-07 07:59 UTC, gzotti commented
The #version must be added only in OpenGL mode. For GL ES, it should remain version-less!

2022-10-07 21:52 UTC, 10110111 commented
Please retest with the new commits.

2022-10-08 03:10 UTC, alex-w commented
> Please retest with the new commits.

Not all shaders are fixed yet

[log.txt](https://github.com/Stellarium/stellarium/files/9738301/log.txt)

2022-10-08 10:26 UTC, 10110111 commented
Please retest.

2022-10-08 10:37 UTC, alex-w commented
> Please retest.

It can be compiled in run now, but without rendering the sky, see 
[log.txt](https://github.com/Stellarium/stellarium/files/9738994/log.txt)

2022-10-08 11:19 UTC, 10110111 commented
Please try now.

2022-10-08 11:46 UTC, alex-w commented
> Please try now.

OK, but ShowMySky shaders should be fixed too, see [log.txt](https://github.com/Stellarium/stellarium/files/9739125/log.txt)

At least standard mode is works now on macOS

2022-10-08 11:54 UTC, 10110111 commented
That was unexpected :) OK, is it fixed now?

2022-10-08 12:55 UTC, 10110111 commented
The second shader should be fixed now.

> `qt.qpa.openglcontext: Could not create NSOpenGLContext with shared context, falling back to unshared context.`

This is strange, especially if it works fine when signed... I'll try some things after we get the signed version to work.

2022-10-08 13:03 UTC, alex-w commented
It crashes now when ShowMySky atmosphere is loading...  see [log.txt](https://github.com/Stellarium/stellarium/files/9739271/log.txt)

2022-10-08 13:09 UTC, 10110111 commented
No crash info got into the log. Is there any kind of backtrace or something?

2022-10-08 13:14 UTC, alex-w commented
> No crash info got into the log. Is there any kind of backtrace or something?

Yes, of course: [log.txt](https://github.com/Stellarium/stellarium/files/9739293/log.txt)

2022-10-08 14:00 UTC, 10110111 commented
Looks like an exception thrown from libShowMySky failed to be caught in Stellarium binary—although there does exist a `try` statement down the call stack. Does macOS need special compiler settings to enable exception propagation between modules? E.g. I had to inlude `/EHs` on Windows to enable stack unwinding.

2022-10-08 14:13 UTC, alex-w commented
> Looks like an exception thrown from libShowMySky failed to be caught in Stellarium binary—although there does exist a `try` statement down the call stack. Does macOS need special compiler settings to enable exception propagation between modules? E.g. I had to include `/EHs` on Windows to enable stack unwinding.

Well, macOS using AppleClang compiler by default, so, all flags for clang should works here too.

2022-10-08 14:24 UTC, 10110111 commented
> P.S. Should I try build master of ShowMySky to test?

You'd need to patch Stellarium for this. Besides, there're no relevant fixes there, so no need to.

2022-10-08 14:41 UTC, 10110111 commented
Could you build CalcMySky with the following patch and get a new log from Stellarium with this libShowMySky?

```diff
diff --git a/ShowMySky/AtmosphereRenderer.cpp b/ShowMySky/AtmosphereRenderer.cpp
index 9b232b0..5efeb67 100644
--- a/ShowMySky/AtmosphereRenderer.cpp
+++ b/ShowMySky/AtmosphereRenderer.cpp
@@ -2229,6 +2229,7 @@ void AtmosphereRenderer::drawSurface(QOpenGLShaderProgram& prog)
 
 void AtmosphereRenderer::resizeEvent(const int width, const int height)
 {
+    qDebug().nospace() << "AtmosphereRenderer::resizeEvent(" << width << ", " << height << ")";
     OGL_TRACE();
 
     viewportSize_=QSize(width,height);
diff --git a/common/util.cpp b/common/util.cpp
index 21cfe3e..61f03ee 100644
--- a/common/util.cpp
+++ b/common/util.cpp
@@ -44,6 +44,7 @@ void checkFramebufferStatus(QOpenGLFunctions_3_3_Core& gl, const char*const fboD
         errorDescription=QObject::tr("unknown error 0x%1").arg(status, 0, 16);
         break;
     }
+    qDebug().noquote() << QObject::tr("%1 is incomplete: %2").arg(fboDescription).arg(errorDescription);
     throw OpenGLError{QObject::tr("%1 is incomplete: %2").arg(fboDescription).arg(errorDescription)};
 }
 
```

2022-10-08 15:13 UTC, alex-w commented
See [dump.txt](https://github.com/Stellarium/stellarium/files/9739579/dump.txt) and [log.txt](https://github.com/Stellarium/stellarium/files/9739580/log.txt)

2022-10-08 15:13 UTC, alex-w commented
See [dump.txt](https://github.com/Stellarium/stellarium/files/9739579/dump.txt) and [log.txt](https://github.com/Stellarium/stellarium/files/9739580/log.txt)

2022-10-08 15:26 UTC, 10110111 commented
What if you use this patch instead?
```diff
diff --git a/ShowMySky/AtmosphereRenderer.cpp b/ShowMySky/AtmosphereRenderer.cpp
index 4edb68f..80d53bc 100644
--- a/ShowMySky/AtmosphereRenderer.cpp
+++ b/ShowMySky/AtmosphereRenderer.cpp
@@ -2227,10 +2227,18 @@ void AtmosphereRenderer::drawSurface(QOpenGLShaderProgram& prog)
     drawSurfaceCallback(prog);
 }
 
-void AtmosphereRenderer::resizeEvent(const int width, const int height)
+void AtmosphereRenderer::resizeEvent(int width, int height)
 {
+    qDebug().nospace() << "AtmosphereRenderer::resizeEvent(" << width << ", " << height << ")";
     OGL_TRACE();
 
+    if(width==0 || height==0)
+    {
+        qWarning().nospace() << "AtmosphereRenderer::resizeEvent(" << width << ", " << height << "): zero area framebuffer specified";
+        width  = std::max(1, width);
+        height = std::max(1, height);
+    }
+
     viewportSize_=QSize(width,height);
     if(!luminanceRadianceFBO_) return;
 
diff --git a/common/util.cpp b/common/util.cpp
index 21cfe3e..61f03ee 100644
--- a/common/util.cpp
+++ b/common/util.cpp
@@ -44,6 +44,7 @@ void checkFramebufferStatus(QOpenGLFunctions_3_3_Core& gl, const char*const fboD
         errorDescription=QObject::tr("unknown error 0x%1").arg(status, 0, 16);
         break;
     }
+    qDebug().noquote() << QObject::tr("%1 is incomplete: %2").arg(fboDescription).arg(errorDescription);
     throw OpenGLError{QObject::tr("%1 is incomplete: %2").arg(fboDescription).arg(errorDescription)};
 }
 
```

2022-10-08 16:01 UTC, alex-w commented
WOW, it works!

2022-10-08 16:58 UTC, alex-w commented
> WOW, it works!

Damn! Switching Preetam->ShowMySky caused crash! See [log.txt](https://github.com/Stellarium/stellarium/files/9739827/log.txt) and [dump.txt](https://github.com/Stellarium/stellarium/files/9739829/dump.txt)

Same time and location (Preetam + ShowMySky):
![stellarium-002](https://user-images.githubusercontent.com/88731/194718787-0c04fb1d-366b-48c3-973b-871ff2a72f50.jpg)
![stellarium-003](https://user-images.githubusercontent.com/88731/194718794-99ce238b-ac4c-451d-af45-0906eaf844a2.jpg)

Rendering ShowMySky is so slow... :(

2022-10-08 17:03 UTC, alex-w commented
In the log: `Unsupported atmosphere model "Притам"`

Please mark items of dropdown list as untranslatable or store and use English names as `Qt::UserRole`

2022-10-08 17:16 UTC, 10110111 commented
> Rendering ShowMySky is so slow

Don't forget about `atmosphere_resolution_reduction` introduced in #2676: it should improve the experience.

> In the log: Unsupported atmosphere model "Притам"

Yeah, I noticed it in previous logs.

2022-10-08 17:21 UTC, alex-w commented
> Don't forget about `atmosphere_resolution_reduction` introduced in #2676: it should improve the experience.

What about adding couple option near selector of atmosphere model as ShowMySky options?

2022-10-08 17:22 UTC, Atque commented
Shouldn’t a MacBook Pro cope with ShowMySky pretty flawlessly?

2022-10-08 17:23 UTC, 10110111 commented
> What about adding couple option near selector of atmosphere model as ShowMySky options?

I'm OK with this. Feel free to do it :) I'm currently busy with OpenGL.

2022-10-08 17:49 UTC, 10110111 commented
> Shouldn’t a MacBook Pro cope with ShowMySky pretty flawlessly?

Judging by a screenshot above, it's about 14 FPS at 2880×1800 resolution. For comparison, on my GeForce GTX 750Ti at 1920×1080 I get 23 FPS. So the Mac performs usably IMO.

2022-10-08 18:08 UTC, 10110111 commented
> Same time and location (Preetam + ShowMySky):

Does it really look as banded as the screenshots show? Could you post a PNG version instead of the artifacted JPEG one?

2022-10-08 18:17 UTC, 10110111 commented
@alex-w Now regarding broken exceptions, [this post](https://github.com/ocaml/ocaml/issues/9026#issuecomment-539641762) says that we indeed need a special build flag. Could you try building vanilla CalcMySky v0.1.0 passing `-DCMAKE_SHARED_LINKER_FLAGS=-Wl,-keep_dwarf_unwind`, and then try reproducing your original crash at startup?

2022-10-08 18:22 UTC, alex-w commented
> > Same time and location (Preetam + ShowMySky):
> 
> Does it really look as banded as the screenshots show? Could you post a PNG version instead of the artifacted JPEG one?

`atmosphere_resolution_reduction = 4`

![stellarium-001](https://user-images.githubusercontent.com/88731/194722018-08c055ca-f02c-4b3e-94cc-eede0aa8f465.png)

2022-10-08 18:29 UTC, 10110111 commented
> atmosphere_resolution_reduction = 4

Funny, now the frame rate with ShowMySky is higher than with Preetham atmosphere :D

The banding is still there though. Did you disable dithering?

2022-10-08 18:37 UTC, alex-w commented
> @alex-w Now regarding broken exceptions, [this post](https://github.com/ocaml/ocaml/issues/9026#issuecomment-539641762) says that we indeed need a special build flag. Could you try building vanilla CalcMySky v0.1.0 passing `-DCMAKE_SHARED_LINKER_FLAGS=-Wl,-keep_dwarf_unwind`, and then try reproducing your original crash at startup?

No lucky, see [dump.txt](https://github.com/Stellarium/stellarium/files/9740070/dump.txt)

2022-10-08 22:05 UTC, 10110111 commented
What happens if you run `showmysky` from the CalcMySky package, passing an invalid path to it? Does it crash, or do you get a message box with a readable error?

2022-10-09 05:11 UTC, alex-w commented
> What happens if you run `showmysky` from the CalcMySky package, passing an invalid path to it? Does it crash, or do you get a message box with a readable error?

This package will crash always on the macOS due 2 reasons: a) this is GUI application and b) this application is not packed by Apple’s rules

2022-10-09 09:03 UTC, alex-w commented
@10110111 please rebase the branch to apply fix for bundling the versioned version of ShowMySky library on macOS

2022-10-09 10:08 UTC, 10110111 commented
> This package will crash always on the macOS due 2 reasons: a) this is GUI application and b) this application is not packed by Apple’s rules

a) Stellarium is also a GUI application
b) When I tried to build CalcMySky with HomeBrew-based dependencies on a friend's (Intel-based) Mac, it worked without any packaging. See the screenshot below.

![photo_5240370232021859785_y](https://user-images.githubusercontent.com/6376882/194750707-6c323b56-7250-4c1d-b72c-eeacbe56aae2.jpg)

2022-10-09 10:15 UTC, alex-w commented
> a) Stellarium is also a GUI application 

Stellarium is bundled :)

> b) When I tried to build CalcMySky with HomeBrew-based dependencies on a friend's (Intel-based) Mac, it worked without any packaging. See the screenshot below.

Fun, let me try it again

2022-10-09 11:01 UTC, alex-w commented
OK, I can build and run `showmysky` tool via CLI when it builded with Qt5 from homebrew. But it say "Failed to load ShowMySky library" after selection `atmosphere/default` directory.

2022-10-09 11:58 UTC, 10110111 commented
> But it say "Failed to load ShowMySky library" after selection atmosphere/default directory.

If you simply run it from the build directory, you may need to use `DYLD_LIBRARY_PATH` environment variable to point to the directory that contains the library. E.g. if you are in the build directory, and there's the library `./ShowMySky/libShowMySky-Qt*.dylib`, then you can run `showmysky` as follows:
```
DYLD_LIBRARY_PATH=./ShowMySky ./ShowMySky/showmysky ~/path/to/atmosphere/default
```

2022-10-09 12:04 UTC, alex-w commented
Oops... I forget about `DYLD_LIBRARY_PATH` on macOS :(

OK, the `showmysky` tool is works now via CLI

2022-10-09 12:06 UTC, 10110111 commented
> OK, the showmysky tool is works now via CLI

Great. Now, does it report errors correctly (e.g. when passed a non-existing directory), or does it crash?

2022-10-09 12:12 UTC, alex-w commented
> Great. Now, does it report errors correctly (e.g. when passed a non-existing directory), or does it crash?

Crash... see [dump.txt](https://github.com/Stellarium/stellarium/files/9741515/dump.txt)

2022-10-09 13:49 UTC, gzotti commented
Testing RPi4:

So far I could only compile without SMS because SMS building failed (did not continue, this was expected.)
Builds and runs with Ubuntu Mate 22.04 and Qt6. 
The Broadcom VC4 driver support is OpenGL 2.1 with GLSL1.2 For reasons I cannot remember we may have increased GLSL minimum to 1.3 and log a warning that something may fail. However, all seems to work, planet shaders, Satun's ring shadows, and even Scenery3D works with some logged issue which (I cannot remember!) may have been here before (caused by switching on PCSS shadow?)
The play about configs is interesting: Now our default format as requested is 3.3 Core, but the driver delivers 2.1 with deprecated functions. (It cannot provide more.)

Here are the logs.
[log_RPi4-U22.04-Scenery3D-OGL3branch.txt](https://github.com/Stellarium/stellarium/files/9741702/log_RPi4-U22.04-Scenery3D-OGL3branch.txt)
[log_RPi4-U22.04-OGL3branch.txt](https://github.com/Stellarium/stellarium/files/9741703/log_RPi4-U22.04-OGL3branch.txt)

I should still test the official Raspberry OS but need to install that first, need to buy a fresh SDcard for that...
RPi3 shall come next, a pure GL ES2.0 system.

2022-10-09 14:29 UTC, 10110111 commented
> need to buy a fresh SDcard for that

You can just dump the current image from the card to a file, install other OSes and play with them, and then restore the original image from the dump. On Unices the dump can be done using `ddrescue` tool. I read it's also usable on Windows (via Cygwin).

2022-10-09 14:59 UTC, gzotti commented
> > need to buy a fresh SDcard for that
> 
> You can just dump the current image from the card to a file, install other OSes and play with them, and then restore the original image from the dump. On Unices the dump can be done using `ddrescue` tool. I read it's also usable on Windows (via Cygwin).

I know. Just wanted to have that second OS anyway. I feel I am copying, updating and installing too many things too often...

2022-10-09 18:01 UTC, gzotti commented
RPi 3B+, Raspbian bullseye:
The OS'es repo has V0.20.4, running at about 16fps (1280x1024 screen).
This branch: builds (with Qt5), runs at launch, but it seems we have increasing issues with textures. All seems OK (although only at 5fps or so), includng planet shaders. but loading nebula textures leads to a segfault. I have seen this previously with HiPS/DSS on this platform, it seems the GPU driver has issues with texture memory handling. I have just found it would support ETC1 texture compression, but how to activate this?
I  built with the OPENGL_DEBUG_LOGGING  set, but this fails at start.

Regarding low fps, this is also quite bad, but I must build master to see if this slowdown is related to this branch.

[log_RPi3-bullseye_OGL3branch.txt](https://github.com/Stellarium/stellarium/files/9742246/log_RPi3-bullseye_OGL3branch.txt)
[log_RPi3-bullseye_0.20.4.txt](https://github.com/Stellarium/stellarium/files/9742247/log_RPi3-bullseye_0.20.4.txt)

2022-10-09 20:37 UTC, gzotti commented
Intel Core i5-4570 (Intel HD 4600, OpenGL 4.3):
I tried to build CalcMySky first, but face problems. 
![grafik](https://user-images.githubusercontent.com/18099873/194778218-7d062655-bb84-4c79-9059-5a00cafc6919.png)
![grafik](https://user-images.githubusercontent.com/18099873/194778242-5e1af487-e995-4076-b01c-b9239a179921.png)
![grafik](https://user-images.githubusercontent.com/18099873/194778267-172780cc-792a-497e-b98e-fabf3dbece88.png)

The line before the red error ("command was ended with code 9009") says "command 'true' misspelled or not found". Any ideas?

2022-10-09 20:47 UTC, 10110111 commented
> command 'true' misspelled or not found

That's something funny. Looks like it's executing `version.sh`, which is a Bourne shell script. `true` is a shell builtin, which makes it strange to not be found.

Are you using `sh` from WSL? I remember having some problems with it. For AppVeyor I explicitly pointed the CI script to use bash that comes with git instead of the WSL one.

2022-10-09 21:36 UTC, gzotti commented
> Are you using `sh` from WSL? I remember having some problems with it. For AppVeyor I explicitly pointed the CI script to use bash that comes with git instead of the WSL one.

Ah, stupid. Actually i had taken notes on my main PC, but not exactly which shell. I remember I had to mix as required. 
But the cmake command was now given in the Windows-own cmd shell. Cmake is from QT's tools directory. Do I have to call a bash installed in my non-WSL cmd environmeint?

2022-10-09 21:50 UTC, 10110111 commented
> Do I have to call a bash installed in my non-WSL cmd environmeint?

Well you don't _call_ it manually, do you? I _think_ you can just make the non-WSL path closer to the beginning in `%PATH%`. In this case the correct bash would be run.

2022-10-09 21:52 UTC, 10110111 commented
@alex-w Please check whether the latest `master` CalcMySky has fixed the crashes.

2022-10-09 22:12 UTC, gzotti commented
Core i5-4570: I will continue the CMC build tomorrow (hopefully). For now, I have built without. It runs, but after activating a scenery3D, it shows weird artifacts (thin lines in the sky) which also remain when I switch off the 3D scene view. 

![grafik](https://user-images.githubusercontent.com/18099873/194781372-49b1e184-0e63-4d66-9ef4-a039cb2850bf.png)

The log has an GL_INVALID_OPERATION
[log_i5-4570_OGL3branch.txt](https://github.com/Stellarium/stellarium/files/9742656/log_i5-4570_OGL3branch.txt)

2022-10-09 22:33 UTC, 10110111 commented
> it shows weird artifacts (thin lines in the sky)

> The log has an GL_INVALID_OPERATION

And none of this happens with `master`, right? And what if you pass `--opengl-compat` option?

2022-10-09 23:58 UTC, alex-w commented
> @alex-w Please check whether the latest `master` CalcMySky has fixed the crashes.

Crash at switching to ShowMySky model - see [log.txt](https://github.com/Stellarium/stellarium/files/9742793/log.txt) and [dump.txt](https://github.com/Stellarium/stellarium/files/9742794/dump.txt)

2022-10-10 00:12 UTC, alex-w commented
Loading ShowMySky model at startup, enable Scenery3D model - crash: [dump.txt](https://github.com/Stellarium/stellarium/files/9742828/dump.txt), [log.txt](https://github.com/Stellarium/stellarium/files/9742831/log.txt)

No crash and no artifacts from Scenery3D when Preetham model is used

2022-10-10 10:49 UTC, 10110111 commented
> Crash at switching to ShowMySky model

Please retest. A message should appear instead of crash. The logs should contain some info on the error.

2022-10-10 11:09 UTC, alex-w commented
> > Crash at switching to ShowMySky model
> 
> Please retest. A message should appear instead of crash. The logs should contain some info on the error.

Please see [log.txt](https://github.com/Stellarium/stellarium/files/9745402/log.txt)

2022-10-10 11:22 UTC, alex-w commented
According to the latest log I can share one observation, which can be important - when Stellarium have 2 opened dialogs and I do screenshot then on the screenshot I see one of dialog as black rectangle. Probably something wrong in the buffers.

2022-10-10 19:22 UTC, 10110111 commented
Please retest with CalcMySky branch `more-gl-error-checks` built in `Debug` mode.

2022-10-10 20:01 UTC, gzotti commented
Sony Vaio VPCZ13V9E: i7-M860 from 2010. This is a pre-optimus with manually switchable Geforce 330M now dysfunctional by Sony's negligence in Win10 drivers, i.e. has only IntelHD. 
This will probably never show ShowMySky, but just run Series 0.* until 2025/Win10-EOL and could still drive a telescope. 

Qt6/master: mesa/black
Qt5.15.2 master runs OK
Qr5.15.2 this branch: black sky. 

[log_i7-M640_master_qt5-angle.txt](https://github.com/Stellarium/stellarium/files/9748628/log_i7-M640_master_qt5-angle.txt)
[log_i7-M640_master-qt6-mesa.txt](https://github.com/Stellarium/stellarium/files/9748629/log_i7-M640_master-qt6-mesa.txt)
[log_i7-M640_OGL3branch_qt5-angle-skyblack.txt](https://github.com/Stellarium/stellarium/files/9748630/log_i7-M640_OGL3branch_qt5-angle-skyblack.txt)

2022-10-10 20:35 UTC, 10110111 commented
> stel.OpenGLArray: Vertex Array Objects are not supported on your hardware (this is not an error)

This is ugly. Even my netbook with GMA950 (OpenGL 1.4) supports VAO (on Ubuntu). And with ANGLE we have to do double work just because it's so limited.

2022-10-10 22:20 UTC, alex-w commented
> Please retest with CalcMySky branch `more-gl-error-checks` built in `Debug` mode.

Please see [log.txt](https://github.com/Stellarium/stellarium/files/9749550/log.txt)

2022-10-10 23:59 UTC, 10110111 commented
Looks like the error happens somewhere _before_ `AtmosphereShowMySky` is created. Could you build Stellarium in debug mode with the following patch applied?

```diff
diff --git a/src/core/modules/AtmosphereShowMySky.cpp b/src/core/modules/AtmosphereShowMySky.cpp
index df33afdf02..3999f3323f 100644
--- a/src/core/modules/AtmosphereShowMySky.cpp
+++ b/src/core/modules/AtmosphereShowMySky.cpp
@@ -425,6 +425,7 @@ AtmosphereShowMySky::AtmosphereShowMySky()
     , viewRayGridBuffer(QOpenGLBuffer::VertexBuffer)
     , luminanceToScreenProgram_(new QOpenGLShaderProgram())
 {
+    StelOpenGL::checkGLErrors(__FILE__,__LINE__);
     indexBuffer.setUsagePattern(QOpenGLBuffer::StaticDraw);
     indexBuffer.create();
     viewRayGridBuffer.setUsagePattern(QOpenGLBuffer::DynamicDraw);
```

2022-10-11 04:27 UTC, alex-w commented
Debug mode: it just works (see [log.txt](https://github.com/Stellarium/stellarium/files/9751071/log.txt))

Release mode: crashes (see [log.txt](https://github.com/Stellarium/stellarium/files/9751097/log.txt))

2022-10-11 09:32 UTC, 10110111 commented
> Loading texture from "/Applications/Stellarium.app/Contents/Resources/atmosphere/default/light-pollution-xyzw.f32"... dimensions from header: 128×64... done
> ShowMySky atmosphere model crashed: GL error on entry to virtual void AtmosphereRenderer::resizeEvent(int, int): Invalid value
> Loading Preetham model
> ShowMySky atmosphere model crashed: GL error on entry to virtual void AtmosphereRenderer::resizeEvent(int, int): Invalid value
> Loading Preetham model
> ShowMySky atmosphere model crashed: GL error on entry to virtual void AtmosphereRenderer::resizeEvent(int, int): Invalid value
> Loading Preetham model
> ShowMySky atmosphere model crashed: GL error on entry to virtual void AtmosphereRenderer::resizeEvent(int, int): Invalid value
> Loading Preetham model
> ShowMySky atmosphere model crashed: GL error on entry to virtual void AtmosphereRenderer::resizeEvent(int, int): Invalid value
> Loading Preetham model
> ShowMySky atmosphere model crashed: GL error on entry to virtual void AtmosphereRenderer::resizeEvent(int, int): Invalid value
> Loading Preetham model
> ShowMySky atmosphere model crashed: GL error on entry to virtual void AtmosphereRenderer::resizeEvent(int, int): Invalid value
> Loading Preetham model
> ShowMySky atmosphere model crashed: GL error on entry to virtual void AtmosphereRenderer::resizeEvent(int, int): Invalid value
> Loading Preetham model
> ShowMySky atmosphere model crashed: GL error on entry to virtual void AtmosphereRenderer::resizeEvent(int, int): Invalid value
> Loading Preetham model
> ShowMySky atmosphere model crashed: GL error on entry to virtual void AtmosphereRenderer::resizeEvent(int, int): Invalid value
> Loading Preetham model
> ShowMySky atmosphere model crashed: GL error on entry to virtual void AtmosphereRenderer::resizeEvent(int, int): Invalid value
> Loading Preetham model
> ShowMySky atmosphere model crashed: GL error on entry to virtual void AtmosphereRenderer::resizeEvent(int, int): Invalid value
> Loading Preetham model
> ShowMySky atmosphere model crashed: GL error on entry to virtual void AtmosphereRenderer::resizeEvent(int, int): Invalid value
> Loading Preetham model
> ShowMySky atmosphere model crashed: GL error on entry to virtual void AtmosphereRenderer::resizeEvent(int, int): Invalid value
> Loading Preetham model
> ShowMySky atmosphere model crashed: GL error on entry to virtual void AtmosphereRenderer::resizeEvent(int, int): Invalid value
> Loading Preetham model
> ShowMySky atmosphere model crashed: GL error on entry to virtual void AtmosphereRenderer::resizeEvent(int, int): Invalid value
> Loading Preetham model
> ShowMySky atmosphere model crashed: GL error on entry to virtual void AtmosphereRenderer::resizeEvent(int, int): Invalid value
> Loading Preetham model

This seems to happen due to dynamic resolution being on. Could you turn it off (and maybe even resolution reduction too)?

2022-10-11 10:08 UTC, 10110111 commented
> This seems to happen due to dynamic resolution being on.

Actually no, this is not the reason. The reason is the atmosphere switch animation. I'll have to redo it. Anyway, it'll still require several retests to debug.

2022-10-11 10:08 UTC, alex-w commented
```
[landscape]
atmosphere_resolution_reduction        = 4
flag_atmosphere_dynamic_resolution  = false
```

Release mode with proposed patch: error (see [log.txt](https://github.com/Stellarium/stellarium/files/9754009/log.txt))

2022-10-11 11:50 UTC, alex-w commented
```
[landscape]
atmosphere_resolution_reduction     = 4
flag_atmosphere_dynamic_resolution  = true
```

ShowMySky (master; release mode) + Stellarium (release mode) = SMS crash ([log.txt](https://github.com/Stellarium/stellarium/files/9754590/log.txt))

ShowMySky (master; release mode) + Stellarium (debug mode) =  Stellarium crash ([log.txt](https://github.com/Stellarium/stellarium/files/9754670/log.txt) + [dump.txt](https://github.com/Stellarium/stellarium/files/9754674/dump.txt))

ShowMySky (master; debug mode) + Stellarium (release mode) = SMS crash ([log.txt](https://github.com/Stellarium/stellarium/files/9754737/log.txt))

ShowMySky (master; debug mode) + Stellarium (debug mode) = all OK ([log.txt](https://github.com/Stellarium/stellarium/files/9754792/log.txt))

2022-10-11 11:52 UTC, 10110111 commented
Could you build release mode versions as `RelWithDebInfo` instead of `Release`?

2022-10-11 12:11 UTC, alex-w commented
> Could you build release mode versions as `RelWithDebInfo` instead of `Release`?

Yes, of course! Both compiled in `RelWithDebInfo` mode: [log.txt](https://github.com/Stellarium/stellarium/files/9754965/log.txt)

2022-10-11 13:32 UTC, 10110111 commented
Let's reduce the amount of test configurations for now:

* CalcMySky should be taken from `more-gl-error-checks` branch and compiled in Debug mode
* Stellarium should be compiled in Debug and RelWithDebInfo variants
* dynamic resolution should be off
* Scenery3d plugin should be disabled

Now, please try the current `gl33-core` Stellarium branch in these two configurations.

2022-10-11 14:01 UTC, alex-w commented
* [x] CalcMySky should be taken from `more-gl-error-checks` branch and compiled in _Debug_ mode
* [x] dynamic resolution should be off
* [x] Scenery3d plugin should be disabled
* [x] Stellarium should be compiled in _Debug_ variant - [log.txt](https://github.com/Stellarium/stellarium/files/9756479/log.txt)
* [x] Stellarium should be compiled in _RelWithDebInfo_ variant - [log.txt](https://github.com/Stellarium/stellarium/files/9756609/log.txt)

2022-10-11 14:17 UTC, 10110111 commented
So, do I understand it correctly: although we get lots of `GL_INVALID_VALUE` errors in the log, Stellarium appears to work fine?

2022-10-11 14:20 UTC, alex-w commented
> So, do I understand it correctly: although we get lots of `GL_INVALID_VALUE` errors in the log, Stellarium appears to work fine?

`RelWithDebInfo`: [log.txt](https://github.com/Stellarium/stellarium/files/9756908/log.txt)

![stellarium-010](https://user-images.githubusercontent.com/88731/195116951-43ece21e-aafd-47f0-acb6-9e91bb984e0c.png)

2022-10-11 22:19 UTC, 10110111 commented
What if you pass `-DCMAKE_CXX_FLAGS=-DQT_NO_DEBUG` and recompile Stellarium in `Debug` mode? This hybrid mode might shed some light on the reason why we don't get any errors in usual Debug mode while we do in Release modes.

2022-10-12 04:24 UTC, alex-w commented
> What if you pass `-DCMAKE_CXX_FLAGS=-DQT_NO_DEBUG` and recompile Stellarium in `Debug` mode? This hybrid mode might shed some light on the reason why we don't get any errors in usual Debug mode while we do in Release modes.

Please see results - first run (selecting ShowMySky model) ([log.txt](https://github.com/Stellarium/stellarium/files/9761470/log.txt)); second run (just startup with defined ShowMySky mode in config.ini) ([log.txt](https://github.com/Stellarium/stellarium/files/9761488/log.txt))

Screenshot from second run:
![stellarium-011](https://user-images.githubusercontent.com/88731/195249570-e6225814-c95a-4e22-9aab-3d18f2e14a1e.png)

2022-10-12 04:25 UTC, alex-w commented
Switching between models is OK now

2022-10-12 08:39 UTC, 10110111 commented
Aha, so this is why we don't get any errors in debug mode: they are explicitly hidden in two places. Please rebuild with the following patch, in complete `Debug` mode without `-DQT_NO_DEBUG`:
```diff
diff --git a/src/StelMainView.cpp b/src/StelMainView.cpp
index 4e58814d47..0357842a44 100644
--- a/src/StelMainView.cpp
+++ b/src/StelMainView.cpp
@@ -368,11 +368,6 @@ protected:
         //important to call this, or Qt may have invalid state after we have drawn (wrong textures, etc...)
         painter->beginNativePainting();
 
-        //fix for bug LP:1628072 caused by QTBUG-56798
-#ifndef QT_NO_DEBUG
-        StelOpenGL::clearGLErrors();
-#endif
-
         //update and draw
         StelApp& app = StelApp::getInstance();
         app.update(dt); // may also issue GL calls
diff --git a/src/core/StelPainter.cpp b/src/core/StelPainter.cpp
index c6550a02b2..5163ade32c 100644
--- a/src/core/StelPainter.cpp
+++ b/src/core/StelPainter.cpp
@@ -808,11 +808,6 @@ void StelPainter::drawText(float x, float y, const QString& str, float angleDeg,
         //important to call this before GL state restore
         painter.end();
 
-        //fix for bug 1628072 caused by QTBUG-56798
-#ifndef QT_NO_DEBUG
-        StelOpenGL::clearGLErrors();
-#endif
-
         //QPainter messes up some GL state, begin/endNativePainting or save/restore does not help
         glState.apply();
     }
```

2022-10-12 09:26 UTC, 10110111 commented
This doesn't make any sense to me.
OK, what does the following command print if you run it from the build directory, where `CMakeCache.txt` resides?
```
grep ^CMAKE_CXX_FLAGS CMakeCache.txt
```

2022-10-12 09:49 UTC, alex-w commented
```
CMAKE_CXX_FLAGS:STRING=
CMAKE_CXX_FLAGS_DEBUG:STRING=-g
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
CMAKE_CXX_FLAGS-ADVANCED:INTERNAL=1
CMAKE_CXX_FLAGS_DEBUG-ADVANCED:INTERNAL=1
CMAKE_CXX_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
CMAKE_CXX_FLAGS_RELEASE-ADVANCED:INTERNAL=1
CMAKE_CXX_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
```

2022-10-12 12:54 UTC, alex-w commented
```
+#define NDEBUG
 #ifndef NDEBUG
```

@10110111  Maybe you meant `#ifdef NDEBUG`?

2022-10-12 13:00 UTC, 10110111 commented
> Maybe you meant #ifdef NDEBUG?

No, this is explicitly a simulation of Release mode definitions in this particular file, while the rest is compiled in normal Debug mode. The ifndef should remain as it is.

2022-10-12 13:07 UTC, alex-w commented
Crash 
[log.txt](https://github.com/Stellarium/stellarium/files/9765084/log.txt)
[dump.txt](https://github.com/Stellarium/stellarium/files/9765093/dump.txt)

2022-10-12 23:53 UTC, 10110111 commented
So, looks like the difference in behavior is due to the difference in placement of `clearGLErrors()` calls in Debug and Release modes. Please try the following patch in Release mode:
```diff
diff --git a/src/StelMainView.cpp b/src/StelMainView.cpp
index 4e58814d47..d88ef3c7e0 100644
--- a/src/StelMainView.cpp
+++ b/src/StelMainView.cpp
@@ -354,6 +354,7 @@ public:
 protected:
     virtual void paint(QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget) Q_DECL_OVERRIDE
     {
+        StelOpenGL::checkGLErrors(__FILE__,__LINE__);
         Q_UNUSED(option)
         Q_UNUSED(widget)
 
@@ -368,10 +369,9 @@ protected:
         //important to call this, or Qt may have invalid state after we have drawn (wrong textures, etc...)
         painter->beginNativePainting();
 
+        StelOpenGL::checkGLErrors(__FILE__,__LINE__);
         //fix for bug LP:1628072 caused by QTBUG-56798
-#ifndef QT_NO_DEBUG
         StelOpenGL::clearGLErrors();
-#endif
 
         //update and draw
         StelApp& app = StelApp::getInstance();
diff --git a/src/core/StelPainter.cpp b/src/core/StelPainter.cpp
index c6550a02b2..52cdc900e8 100644
--- a/src/core/StelPainter.cpp
+++ b/src/core/StelPainter.cpp
@@ -44,6 +44,7 @@
 
 static const int TEX_CACHE_LIMIT = 7000000;
 
+#define NDEBUG
 #ifndef NDEBUG
 QMutex* StelPainter::globalMutex = new QMutex();
 #endif
@@ -767,6 +768,8 @@ void StelPainter::drawText(float x, float y, const QString& str, float angleDeg,
     }
     else
     {
+        StelOpenGL::checkGLErrors(__FILE__,__LINE__);
+
         QOpenGLPaintDevice device;
         device.setSize(QSize(prj->getViewportWidth(), prj->getViewportHeight()));
         // This doesn't seem to work correctly, so implement the hack below instead.
@@ -808,10 +811,9 @@ void StelPainter::drawText(float x, float y, const QString& str, float angleDeg,
         //important to call this before GL state restore
         painter.end();
 
+        StelOpenGL::checkGLErrors(__FILE__,__LINE__);
         //fix for bug 1628072 caused by QTBUG-56798
-#ifndef QT_NO_DEBUG
         StelOpenGL::clearGLErrors();
-#endif
 
         //QPainter messes up some GL state, begin/endNativePainting or save/restore does not help
         glState.apply();
```

2022-10-13 02:59 UTC, alex-w commented
It works in Release mode [log.txt](https://github.com/Stellarium/stellarium/files/9770040/log.txt)

2022-10-13 09:27 UTC, 10110111 commented
OK, lots of errors are visible now. What if you try the same patch on `master`?

2022-10-13 11:16 UTC, alex-w commented
> OK, lots of errors are visible now. What if you try the same patch on `master`?

No errors, except ShowMySky: [log.txt](https://github.com/Stellarium/stellarium/files/9776047/log.txt)

2022-10-13 13:47 UTC, 10110111 commented
Let's see which modules generate these errors. Please try the following patch in Release mode on `gl33-core` branch.
```diff
diff --git a/src/StelMainView.cpp b/src/StelMainView.cpp
index 4e58814d47..d88ef3c7e0 100644
--- a/src/StelMainView.cpp
+++ b/src/StelMainView.cpp
@@ -354,6 +354,7 @@ public:
 protected:
     virtual void paint(QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget) Q_DECL_OVERRIDE
     {
+        StelOpenGL::checkGLErrors(__FILE__,__LINE__);
         Q_UNUSED(option)
         Q_UNUSED(widget)
 
@@ -368,10 +369,9 @@ protected:
         //important to call this, or Qt may have invalid state after we have drawn (wrong textures, etc...)
         painter->beginNativePainting();
 
+        StelOpenGL::checkGLErrors(__FILE__,__LINE__);
         //fix for bug LP:1628072 caused by QTBUG-56798
-#ifndef QT_NO_DEBUG
         StelOpenGL::clearGLErrors();
-#endif
 
         //update and draw
         StelApp& app = StelApp::getInstance();
diff --git a/src/core/StelApp.cpp b/src/core/StelApp.cpp
index 455212f07b..5b507f0cb1 100644
--- a/src/core/StelApp.cpp
+++ b/src/core/StelApp.cpp
@@ -809,6 +809,7 @@ void StelApp::draw()
     if (!initialized)
         return;
 
+    StelOpenGL::checkGLErrors(__FILE__,__LINE__);
     //find out which framebuffer is the current one
     //this is usually NOT the "zero" FBO, but one provided by QOpenGLWidget
     GLint drawFbo;
@@ -822,7 +823,10 @@ void StelApp::draw()
     const QList<StelModule*> modules = moduleMgr->getCallOrders(StelModule::ActionDraw);
     for (auto* module : modules)
     {
+        qDebug().nospace().noquote() << "\n" << module->objectName() << "::draw()";
+        StelOpenGL::checkGLErrors(__FILE__,__LINE__);
         module->draw(core);
+        StelOpenGL::checkGLErrors(__FILE__,__LINE__);
     }
     core->postDraw();
 #ifdef ENABLE_SPOUT
@@ -831,6 +835,8 @@ void StelApp::draw()
         spoutSender->captureAndSendFrame(static_cast<GLuint>(drawFbo));
 #endif
     applyRenderBuffer(static_cast<GLuint>(drawFbo));
+
+    StelOpenGL::checkGLErrors(__FILE__,__LINE__);
 }
 
 /*************************************************************************
diff --git a/src/core/StelPainter.cpp b/src/core/StelPainter.cpp
index c6550a02b2..92b9f77eae 100644
--- a/src/core/StelPainter.cpp
+++ b/src/core/StelPainter.cpp
@@ -767,6 +767,8 @@ void StelPainter::drawText(float x, float y, const QString& str, float angleDeg,
     }
     else
     {
+        StelOpenGL::checkGLErrors(__FILE__,__LINE__);
+
         QOpenGLPaintDevice device;
         device.setSize(QSize(prj->getViewportWidth(), prj->getViewportHeight()));
         // This doesn't seem to work correctly, so implement the hack below instead.
@@ -808,10 +810,9 @@ void StelPainter::drawText(float x, float y, const QString& str, float angleDeg,
         //important to call this before GL state restore
         painter.end();
 
+        StelOpenGL::checkGLErrors(__FILE__,__LINE__);
         //fix for bug 1628072 caused by QTBUG-56798
-#ifndef QT_NO_DEBUG
         StelOpenGL::clearGLErrors();
-#endif
 
         //QPainter messes up some GL state, begin/endNativePainting or save/restore does not help
         glState.apply();
```

2022-10-13 14:17 UTC, alex-w commented
Weird results: [log.txt](https://github.com/Stellarium/stellarium/files/9777582/log.txt)

2022-10-13 14:43 UTC, 10110111 commented
Nothing weird, quite fine. I've pushed a patch to look deeper, please try it in Release mode.

2022-10-13 15:25 UTC, alex-w commented
> Nothing weird, quite fine. I've pushed a patch to look deeper, please try it in Release mode.

Please see [log.txt](https://github.com/Stellarium/stellarium/files/9778215/log.txt)

2022-10-13 19:46 UTC, 10110111 commented
We are getting close. I've pushed more checks, please retest.

2022-10-13 20:54 UTC, gzotti commented
Great to read the progress. I am currently not available. Hopefully testing my computer zoo again on Sunday.

2022-10-13 22:51 UTC, 10110111 commented
@gzotti your testing is not required yet. I've seen from one your report that VAO support may be unavailable on the target platforms, and this problem is still not addressed. What's currently being done is just a chase for OpenGL errors on macOS.

2022-10-14 03:25 UTC, alex-w commented
> We are getting close. I've pushed more checks, please retest.

Please see [log.txt](https://github.com/Stellarium/stellarium/files/9782211/log.txt)

2022-10-14 09:48 UTC, 10110111 commented
Funny, it didn't clarify anything. Apparently, the problem is elsewhere. I've pushed another patch, please retest.

2022-10-14 09:49 UTC, 10110111 commented
BTW, do constellation lines look as they should?

2022-10-14 10:12 UTC, alex-w commented
> BTW, do constellation lines look as they should?

Please see [log.txt](https://github.com/Stellarium/stellarium/files/9784883/log.txt)

![stellarium-012](https://user-images.githubusercontent.com/88731/195822450-66d7d16b-f30c-4f9e-978a-be781d2d9747.png)

2022-10-14 11:36 UTC, 10110111 commented
OK, I see. `glLineWidth` with argument >1 is unsupported in Core profile. Do you get wider lines with `--opengl-compat` option?

2022-10-14 15:48 UTC, 10110111 commented
I've stubbed the offending call, it shouldn't generate these `GL_INVALID_VALUE` errors now. Please retest and in particular try atmosphere switching. I'll try to chase down the origin of the framebuffer errors.

2022-10-14 16:52 UTC, alex-w commented
Model switching is OK: [log.txt](https://github.com/Stellarium/stellarium/files/9788472/log.txt)

2022-10-14 18:31 UTC, 10110111 commented
Please retest model switching with the new commit.

2022-10-14 19:21 UTC, alex-w commented
> OK, I see. `glLineWidth` with argument >1 is unsupported in Core profile.

This is bad news. This feature is used for demonstrating constellations and asterisms via projectors - how we can change width of line in Core profile? Or can we replace `glLineWidth`?

2022-10-14 19:27 UTC, 10110111 commented
> how we can change width of line in Core profile? Or can we replace glLineWidth?

The general recommendation is to draw quads instead of lines. This makes it a bit harder to make them smooth (must rely on multisampling, which is currently disabled by default in Stellarium on all platforms). OTOH, if we enable it by default, using a moderate number of samples per pixel like 8, this will make the results a bit more correct when lines intersect—compared to Wu-like algorithms, which don't care about already present primitives while rendering a new one.

2022-10-14 20:24 UTC, 10110111 commented
> Where you found limitations for glLineWidth?

OpenGL 3.3 Core specification, chapter E.2.1.

2022-10-14 20:39 UTC, gzotti commented
> > Where you found limitations for glLineWidth?
> 
> OpenGL 3.3 Core specification, chapter E.2.1.

Yes, I remember also having read that, and it may have been one of the reasons not to invest much time going for Core profile just because it was deemed "cleaner". Also GLES (and with it, Qt5/ANGLE) does not have it, but these are IMHO indeed systems of less importance. On "genuine" OpenGL systems I would still like to see this feature preserved, i.e. Compatibility profile must remain at least as option on systems where it is principally available. (Macs differ, as always...) Or the feature implemented as thin quads, indeed. (As method in StelPainter, with simple to adapt code! This could then bring back dotted lines etc...)

2022-10-15 06:37 UTC, alex-w commented
> Please retest model switching with the new commit.

First run (switching to ShowMySky model): [log.txt](https://github.com/Stellarium/stellarium/files/9791319/log.txt)

Second run (use ShowMySky model at startup): [log.txt](https://github.com/Stellarium/stellarium/files/9791326/log.txt)

P.S. Both are OK

2022-10-15 22:07 UTC, 10110111 commented
Please re-run with the updated checks.

2022-10-15 22:09 UTC, 10110111 commented
> On "genuine" OpenGL systems I would still like to see this feature preserved

What is it used, aside from widening the lines for high-DPI scaling?

> This could then bring back dotted lines etc.

When were they in use and for what? Why were they dropped?

2022-10-16 00:15 UTC, gzotti commented
> > On "genuine" OpenGL systems I would still like to see this feature preserved
> 
> What is it used, aside from widening the lines for high-DPI scaling?

Not necessarily for high-DPI. I like to have wider lines (2-3) on FullHD. 

> 
> > This could then bring back dotted lines etc.
> 
> When were they in use and for what? Why were they dropped?

I think we tried them for borders or asterisms, but line style is also not available on ANGLE (OpenGL ES2.0), so it was no use. I read somewhere that thick lines or other line style has to be implemented in a shader, and did not continue investigating as "line thickness" seemed good enough, and other things were more important problems to solve.

2022-10-16 00:15 UTC, 10110111 commented
@gzotti How do you get ANGLE to work? Do you use the dedicated shortcut? What happens if you run the "normal", non-ANGLE, shortcut on your Sony laptop?

Why I'm asking is because the mechanism that's supposed to enable ANGLE doesn't work for me via `--angle-mode` option and its siblings, because they set the `QT_OPENGL` environment variable _after_ `QGuiApplication` is created, while it's this class that reads this environment variable. Setting `QT_OPENGL` manually does work.

2022-10-16 00:39 UTC, gzotti commented
> @gzotti How do you get ANGLE to work (on `master`)? Do you use the dedicated shortcut? What happens if you run the "normal", non-ANGLE, shortcut on your Sony laptop?

Without the environment variable set to ANGLE (and setting it to desktop), the Sony just reports insufficient OpenGL level. Not sure if it just quits then, can try tomorrow. The bad thing its, it was crippled by Sony's unwillingness to support their products when still technically OK. The laptop was officially not supported with Win10, however, somebody found a way to keep the Intel/Geforce hybrid system working with manually patched driver .inf files. Just the switch did not work any longer, and it needed a reboot to actually switch GPUs. I could live with that. But some Win10 version update broke the Geforce driver again, and that driver hack website has unfortunately vanished. OK, bad luck. But still, this is a Core-i7 of the first generation and else a nice little system to use, and I am pretty sure there are still millions of those CPUs around. This is a GPU that was blacklisted by Qt to immediately initialize to ANGLE with Qt5. On Qt6, it runs Mesa mode, i.e. noticeably much lower fps, and also just OpenGL3.0. 

 
> Why I'm asking is because the mechanism that's supposed to enable ANGLE doesn't work for me via `--angle-mode` option and its siblings, because they set the `QT_OPENGL` environment variable _after_ `QGuiApplication` is created, while it's this class that reads this environment variable. Setting `QT_OPENGL` manually does work.

Yes, the setting of the env vars has worked earlier (when I introduced them years ago), but at some point something changed, and the --angle-mode etc no longer work. See wiki entries about "Common Problems" on Github.

2022-10-16 07:31 UTC, alex-w commented
> Please re-run with the updated checks.

Please see [log.txt](https://github.com/Stellarium/stellarium/files/9793830/log.txt)

2022-10-16 07:38 UTC, alex-w commented
> > On "genuine" OpenGL systems I would still like to see this feature preserved
> 
> What is it used, aside from widening the lines for high-DPI scaling?

Not only HDPI systems - for projectors it's necessary too.

> 
> > This could then bring back dotted lines etc.
> 
> When were they in use and for what? Why were they dropped?

See screenshot from version 0.11.4:
![stellarium-000](https://user-images.githubusercontent.com/88731/196023965-bc5ce113-510b-489d-93b5-614adfdac12a.png)

In series 0.12.x rendering engine was seriously updated and we "lost" rendering the stylized lines.

2022-10-16 10:49 UTC, 10110111 commented
Please retest with updated CalcMySky `master`.

2022-10-16 11:12 UTC, alex-w commented
> Please retest with updated CalcMySky `master`.

First run (switching to ShowMySky model): [log.txt](https://github.com/Stellarium/stellarium/files/9794290/log.txt)

Second run (use ShowMySky model at startup): [log.txt](https://github.com/Stellarium/stellarium/files/9794292/log.txt)

P.S. Both are compiled in `Release` mode and both are OK

2022-10-16 13:13 UTC, 10110111 commented
Great. So the remaining problems now are the `glLineWidth` and VAO@ANGLE.

@gzotti Am I right that in ANGLE mode dithering doesn't work? I've just tried it via Wine and was surprised to see banded image.

2022-10-16 13:21 UTC, gzotti commented
Hmm, dithering had ugly banding on ANGLE (but not on my GLES2 Odroid (Mali)!) before you changed it to the new algorithm. Must check again, just wanted to dig out my Vaio again.... BTW the i5-4570 also had no VAO I think.

2022-10-16 13:26 UTC, 10110111 commented
> BTW the i5-4570 also had no VAO I think.

Not so simple: if you judged from the logs, this may be misleading because Stellarium used to have Intel explicitly blacklisted for VAO (which makes no sense for Macs of course).

2022-10-16 17:20 UTC, gzotti commented
Here are logs from the Vaio. I built without SMS as we won't get it anyhow. Sky looks good, but we have errors in the log. 

[log_i7-M640_OGL3branch1016_qt5-angle-skyOK-but-OGLerrors.txt](https://github.com/Stellarium/stellarium/files/9795265/log_i7-M640_OGL3branch1016_qt5-angle-skyOK-but-OGLerrors.txt)
[log_i7-M640_master1016_qt5-angleDX11.txt](https://github.com/Stellarium/stellarium/files/9795266/log_i7-M640_master1016_qt5-angleDX11.txt)
[log_i7-M640_0.22.3-AngleDX9.txt](https://github.com/Stellarium/stellarium/files/9795267/log_i7-M640_0.22.3-AngleDX9.txt)
[log_i7-M640_0.21.3-AngleDX11.txt](https://github.com/Stellarium/stellarium/files/9795268/log_i7-M640_0.21.3-AngleDX11.txt)
[log_i7-M640_0.22.3-AngleDX11.txt](https://github.com/Stellarium/stellarium/files/9795269/log_i7-M640_0.22.3-AngleDX11.txt)

2022-10-16 19:41 UTC, 10110111 commented
@gzotti Now both in `master` and in this branch the options like `--mesa-mode` etc. should work.

2022-10-16 22:26 UTC, gzotti commented
Yes, the early setting of angle envvars works again! OTOH, on the Valo, I now see neither daylight sky nor stars! Moon, planets MilkyWay, DSOs are OK, 
[log_i7-M640_OGL3branch1016_qt5-angleOK_butNoSkyNoStars.txt](https://github.com/Stellarium/stellarium/files/9795809/log_i7-M640_OGL3branch1016_qt5-angleOK_butNoSkyNoStars.txt)

2022-10-16 23:01 UTC, 10110111 commented
> I now see neither daylight sky nor stars

Yup, this is expected. It's due to the unconditional use of VAO.

2022-10-16 23:19 UTC, gzotti commented
> > I now see neither daylight sky nor stars
> 
> Yup, this is expected. It's due to the unconditional use of VAO.

Note that running "pure" software GL (MESA) on Windows (OpenGL 3.0) currently has fully black screen.

[log_master_MESA.txt](https://github.com/Stellarium/stellarium/files/9795913/log_master_MESA.txt)

2022-10-16 23:36 UTC, 10110111 commented
> Note that running "pure" software GL (MESA) on Windows (OpenGL 3.0) currently has fully black screen.

I wonder why Qt provides such an ancient version of Mesa: 11.2.2 was released in 2016 and the project has since grown to [support OpenGL 4.6](https://mesamatrix.net/#OpenGL) in its llvmpipe renderer.

> I now see neither daylight sky nor stars.

I've pushed a fix for stars :)
Night mode and atmosphere still have to be fixed.

2022-10-17 01:04 UTC, gzotti commented
+1 on ancient Mesa version. We should probably build a newer version from the llvmpipe site.

2022-10-17 10:44 UTC, 10110111 commented
OK, so now it should work in all cases:
* Windows, Linux, macOS with ShowMySky
* Windows+ANGLE without ShowMySky
* Windows+Mesa without ShowMySky (due to very old Mesa version)

What I didn't test is all this with Qt6.
What remains unsolved is wide lines.

Dithering should work universally well (even on `master`, I've pushed the fix there too). If the sky is banded by default in some configuration, it's a bug.

2022-10-17 13:10 UTC, gzotti commented
OK, works on my old Vaio (Qt5/Angle). Dithering is very good now.

2022-10-17 21:03 UTC, gzotti commented
> +1 on ancient Mesa version. We should probably build a newer version from the llvmpipe site.

This may be useful:
https://wiki.qt.io/MesaLlvmpipe

else
https://github.com/pal1000/mesa-dist-win
https://docs.mesa3d.org/drivers/llvmpipe.html

2022-10-18 00:33 UTC, 10110111 commented
So now all the problems have been solved. Wide lines in the Core profile are implemented using a geometry shader.

Now this PR needs thorough testing on all the configurations that Stellarium intends to support.

2022-10-18 07:57 UTC, alex-w commented
macOS/Qt6 - all works OK (ShowMySky + line width)

2022-10-18 08:39 UTC, gzotti commented
Main system (Win10/Geforce 960M) starts with OpenGL3.3Core. Thank you for the wide lines, but they now look aliased. Where did we have the multisampling, any manual entry in config.ini? 
Also, it is now possible to extend the wide lines to OpenGL ES2 systems? (I did not check, but see shader version #330. 

I switched on Scenery3D. Big issue: Stars are missing. Planets are still here.

Another big issue: After once switching on a scene in Scenery3D, the sky sometimes shows "slices" in the dome. Interestingly enough, this is only in live view. A screenshot has them covered. A screenshot with another program shows it (around the moon):
![grafik](https://user-images.githubusercontent.com/18099873/196378565-11d0875e-e448-4fc6-a209-483abcc5bd55.png)

These slices also remain when switching back to Preetham. 

[log_Geforce960M_OpenGL3.txt](https://github.com/Stellarium/stellarium/files/9808506/log_Geforce960M_OpenGL3.txt)

2022-10-18 08:44 UTC, alex-w commented
macOS/Qt5 - fails - [log.txt](https://github.com/Stellarium/stellarium/files/9808543/log.txt)

2022-10-18 10:05 UTC, 10110111 commented
> Where did we have the multisampling, any manual entry in config.ini?

`[video]/multisampling`

> Also, it is now possible to extend the wide lines to OpenGL ES2 systems?

Not without more work. [`GL_EXT_geometry_shader`](https://registry.khronos.org/OpenGL/extensions/EXT/EXT_geometry_shader.txt) requires GL ES 3.1. If not via geometry shader, this will require pre-processing of the geometry on the CPU.

> I switched on Scenery3D. Big issue: Stars are missing.

So the stars were there before you enabled Scenery3d, and then disappeared?

Was all this in Core profile desktop GL? What if you use `--opengl-compat` option?

2022-10-18 11:41 UTC, gzotti commented
> > Also, it is now possible to extend the wide lines to OpenGL ES2 systems?
> 
> Not without more work. [`GL_EXT_geometry_shader`](https://registry.khronos.org/OpenGL/extensions/EXT/EXT_geometry_shader.txt) requires GL ES 3.1. If not via geometry shader, this will require pre-processing of the geometry on the CPU.

OK, not critically important. 
 
> > I switched on Scenery3D. Big issue: Stars are missing.
> 
> So the stars were there before you enabled Scenery3d, and then disappeared?

Yes
 
> Was all this in Core profile desktop GL? What if you use `--opengl-compat` option?

Same behaviour unfortunately. It starts with SMS sky and stars, but when I activate Scenery3D, stars vanish. And the sky shows these strange cracks.

[log_Geforce960M_OpenGLcompat.txt](https://github.com/Stellarium/stellarium/files/9809899/log_Geforce960M_OpenGLcompat.txt)

2022-10-18 12:16 UTC, 10110111 commented
Do the problems with Scenery3d happen if you start with Preetham atmosphere and never switch to ShowMySky?

2022-10-18 12:31 UTC, gzotti commented
> Do the problems with Scenery3d happen if you start with Preetham atmosphere and never switch to ShowMySky?

Uh, yes! Tested in Compat mode and (new) standard Core3.3. The stars remain off even when scenery3D is then again disabled.

2022-10-18 13:15 UTC, 10110111 commented
> Uh, yes! Tested in Compat mode and (new) standard Core3.3.

OK, then it'd be very helpful if you could run `git bisect` testing between 441061577482a17cda6849cfb2515da8ebc0e170 and 649de9cd9e7ed825a802b67e804d2200cadce8de to determine which commit broke it. This will require about 3 rebuilds. You'll need to pass `--opengl-compat` to stellarium each time, because only the last commit covers all requirements of the Core profile.

(If you don't know how to use git-bisect, see [this Wine tutorial](https://wiki.winehq.org/Regression_Testing#Running_the_bisection) on regression testing.)

2022-10-18 14:54 UTC, gzotti commented
Thanks for the tutorial, I was really not aware of this command (but used a similar strategy manually earlier).

![grafik](https://user-images.githubusercontent.com/18099873/196465313-29ca39fe-c038-4347-b847-5950e6f9a26d.png)

2022-10-18 18:57 UTC, gzotti commented
Patch over the bad commit or over current head?

2022-10-18 19:11 UTC, gzotti commented
[log_M960_3.3core_patched.txt](https://github.com/Stellarium/stellarium/files/9814312/log_M960_3.3core_patched.txt)
[log_M960_4.6compat_patched.txt](https://github.com/Stellarium/stellarium/files/9814313/log_M960_4.6compat_patched.txt)
![stellarium-028](https://user-images.githubusercontent.com/18099873/196522370-0198e6f0-0f5b-468a-93cd-1b226722c88b.jpg)

2022-10-18 19:56 UTC, 10110111 commented
Does anything change visually if you apply this (run in compat mode)?
```diff
diff --git a/plugins/Scenery3d/src/S3DRenderer.cpp b/plugins/Scenery3d/src/S3DRenderer.cpp
index fe23ad131b..76a84f4ff2 100644
--- a/plugins/Scenery3d/src/S3DRenderer.cpp
+++ b/plugins/Scenery3d/src/S3DRenderer.cpp
@@ -1205,7 +1205,6 @@ void S3DRenderer::drawFromCubeMap()
     //transform vertices on CPU side - maybe we could do this multithreaded, kicked off at the beginning of the frame?
     altAzProjector->project(cubeVertices.count(),cubeVertices.constData(),transformedCubeVertices.data());
 
-    vao.bind();
     //setup shader params
     projectionMatrix = altAzProjector->getProjectionMatrix().convertToQMatrix();
     cubeShader->setUniformValue(shaderManager.uniformLocation(cubeShader,ShaderMgr::UNIFORM_MAT_PROJECTION), projectionMatrix);
```

2022-10-18 20:31 UTC, gzotti commented
Yay!
![stellarium-030](https://user-images.githubusercontent.com/18099873/196537604-41e484b6-1732-4cac-95c4-9e9b5a739d6b.jpg)
[log.txt](https://github.com/Stellarium/stellarium/files/9814866/log.txt)

2022-10-18 20:49 UTC, 10110111 commented
That's actually bad :)
This line was necessary for Core profile. I wonder why it breaks things on your machine, because I failed to reproduce it on my machines, including an NVIDIA ION-based one (EEEPC 1015PN).

2022-10-18 20:50 UTC, 10110111 commented
Could you post your `config.ini`? Maybe some things are enabled that trigger this problem...

2022-10-18 21:02 UTC, gzotti commented
[config - M960.ini.txt](https://github.com/Stellarium/stellarium/files/9815112/config.-.M960.ini.txt)

2022-10-18 21:20 UTC, 10110111 commented
@alex-w 
> macOS/Qt5 - fails

Does `showmysky` tool also fail in a similar way?

2022-10-18 21:29 UTC, 10110111 commented
@gzotti Please try the following patch in Core mode.
```diff
diff --git a/plugins/Scenery3d/src/S3DRenderer.cpp b/plugins/Scenery3d/src/S3DRenderer.cpp
index fe23ad131b..892169d9fb 100644
--- a/plugins/Scenery3d/src/S3DRenderer.cpp
+++ b/plugins/Scenery3d/src/S3DRenderer.cpp
@@ -1257,11 +1257,11 @@ void S3DRenderer::drawFromCubeMap()
     }
     cubeIndexBuffer.release();
 
-    vao.release();
-
     cubeShader->disableAttributeArray(StelOpenGLArray::ATTLOC_TEXCOORD);
     cubeShader->disableAttributeArray(StelOpenGLArray::ATTLOC_VERTEX);
 
+    vao.release();
+
     glDisable(GL_CULL_FACE);
     glDisable(GL_DEPTH_TEST);
     glDisable(GL_BLEND);
```

2022-10-18 21:52 UTC, gzotti commented
No, doesn't work. If I only change these lines, the stars are gone. If  also comment away the vao.bind() above, stars are here but the scenery is not visible. 

Sorry, I must quit for today.  Good night.

2022-10-18 23:28 UTC, 10110111 commented
I'm pretty sure that it's a driver bug, and I'm having a hard time trying to work around it. Could you try upgrading the driver to version 522.25 that nvidia.com provides for GeForce 960M?

2022-10-19 10:29 UTC, gzotti commented
New drivers, same problem. No stars after switching on Scenery3D. I have not applied any patches to current branch head. 
[log.txt](https://github.com/Stellarium/stellarium/files/9819451/log.txt)
[log_522_Compat46.txt](https://github.com/Stellarium/stellarium/files/9819570/log_522_Compat46.txt)

I will test on an older Geforce 580M which used to be a "great" system.

2022-10-19 11:58 UTC, gzotti commented
Bad news. Geforce 580M, latest drivers. 
[log_580M_3.3core.txt](https://github.com/Stellarium/stellarium/files/9820164/log_580M_3.3core.txt)
[log_580M_4.6compat.txt](https://github.com/Stellarium/stellarium/files/9820165/log_580M_4.6compat.txt)

Both have vanishing stars on activation of scenery3D, and show the "cracks" in the sky.
 
![stellarium-001](https://user-images.githubusercontent.com/18099873/196684393-89cbcef4-69e8-4f94-822b-2b4407e8c8c9.png)

2022-10-19 12:58 UTC, 10110111 commented
Interesting, here we do have the scenery, although the stars become stripes. Do you observe this problem in Mesa mode?

2022-10-19 13:01 UTC, 10110111 commented
Also, what happens if you zoom into these stripes? How do they look when magnified?

2022-10-19 13:18 UTC, alex-w commented
> Does `showmysky` tool also fail in a similar way?

No, `showmysky` tool works as expected

2022-10-19 13:26 UTC, gzotti commented
These stripes are not related to the stars AFAICS. These are the strange cracks I was mentioning. 
The are fast to appear and vanish, I cannot zoom in on them, they look like unclosed gaps. However, I see none of our  coordinate grid that they would follow. 

https://user-images.githubusercontent.com/18099873/196703029-309e0e90-656a-400b-80ce-2eb400c790ae.mp4

Given that Scenery3D makes a huge difference between Perspective and the other projections, I tried with perspective. Even here the cracks show. When I move the scene with the mouse, the cracks move a bit, then vanish and appear elsewhere.

2022-10-19 13:48 UTC, gzotti commented
New test on my Intel i5-4570. Core3.3 profile. The same behaviour: stars vanish on activating Scenery3D. And the cracks. Here I move the scene and then time.

https://user-images.githubusercontent.com/18099873/196707312-a206fa09-8f2b-4427-ac07-f84d075d5aa5.mp4

The compat run shows just a black screen :-( Log says 3.3 compat. The hardware earlier (V1.22.3) reported 4.3 compat. 

[log_i5-4570_OGLcompat_black.txt](https://github.com/Stellarium/stellarium/files/9821016/log_i5-4570_OGLcompat_black.txt)
[log_i5-4570_3.3core.txt](https://github.com/Stellarium/stellarium/files/9821018/log_i5-4570_3.3core.txt)

2022-10-19 15:27 UTC, 10110111 commented
I've finally reproduced it on an Intel GPU. This problem only happens in Windows Qt6 version but not Qt5 (tested 32-bit), and these stripes are actually stars: they disappear when I press <kbd>S</kbd> and reappear on a repeated press. Don't know the reason yet, still investigating.

2022-10-19 18:15 UTC, gzotti commented
Uh, indeed. No problem on 960M with Qt5/3.3Core (64bit).  The cracks indeed appear in the stars pass, but they are too regular, geometrically speaking, to be stars.

2022-10-19 23:39 UTC, 10110111 commented
From what I've studied, `glGenVertexArrays` appears to return the same name twice in a row. Between these two calls (one in `StelSkyDrawer` as called from `StelApp::init`, another in `S3DRenderer` as called from `StelApp::initPlugIns`) there is a switch of OpenGL context (via `wglMakeCurrent`).

Why this happens is still to be determined. I suspect the manipulations of fullscreen etc. state between these two initializations lead to this context switch. (`StelMainView::init()` is a mess.) To check that I'll need another CI recompilation which takes 40 minutes, so going AFK for the night.

2022-10-20 13:20 UTC, 10110111 commented
Now the disappearing stars should be fixed. This commit, d90b5b10a50c8b235d1f48ef65b3006707a5ea5e, is not a nice solution, but it will work for now.

If done properly, it probably would affect #2755 and maybe something else (there are comments about previously applied kludges for other issues).

2022-10-20 13:44 UTC, alex-w commented
> Now the disappearing stars should be fixed. This commit, [d90b5b1](https://github.com/Stellarium/stellarium/commit/d90b5b10a50c8b235d1f48ef65b3006707a5ea5e), is not a nice solution, but it will work for now.
> 
> If done properly, it probably would affect #2755 and maybe something else (there are comments about previously applied kludges for other issues).

Notification in the log:
```
Dubious result: Landscape  "Guereins"  not calibrated. Opacity test represents mathematical horizon only.
Initializing planets GL shaders... 
"StelPainter: Warnings while linking transformShaderProgram shader program:\nWARNING: Could not find vertex shader attribute 'texCoord' to match BindAttributeLocation request.\nWARNING: Could not find vertex shader attribute 'normalIn' to match BindAttributeLocation request.\n"
/Users/aw/stellarium/src/core/modules/AtmosphereShowMySky.cpp:606: OpenGL error: 1282 (GL_INVALID_OPERATION)
```

2022-10-20 16:25 UTC, 10110111 commented
> `/Users/aw/stellarium/src/core/modules/AtmosphereShowMySky.cpp:606: OpenGL error: 1282 (GL_INVALID_OPERATION)`

It would be extremely useful if you could build a patched debug version of Qt, with the following patch, and then run Stellarium with it to reproduce this error. This way we'll know the exact stack trace of where the error originates.

Otherwise we'll have to once again locate the origin via manual ping-pong of posts here.

```diff
diff --git a/qtbase/src/gui/opengl/qopenglfunctions.h b/qtbase/src/gui/opengl/qopenglfunctions.h
index c288df53b5..7bb317fd68 100644
--- a/qtbase/src/gui/opengl/qopenglfunctions.h
+++ b/qtbase/src/gui/opengl/qopenglfunctions.h
@@ -54,7 +54,7 @@
 #include <QtGui/qopengl.h>
 #include <QtGui/qopenglcontext.h>
 
-//#define Q_ENABLE_OPENGL_FUNCTIONS_DEBUG
+#define Q_ENABLE_OPENGL_FUNCTIONS_DEBUG
 
 #if QT_CONFIG(opengles2)
 typedef double GLdouble;
@@ -68,7 +68,7 @@ typedef double GLdouble;
         unsigned clamped = qMin(unsigned(error - GL_INVALID_ENUM), 4U); \
         const char *errors[] = { "GL_INVALID_ENUM", "GL_INVALID_VALUE", "GL_INVALID_OPERATION", "Unknown" }; \
         printf("GL error at %s:%d: %s\n", __FILE__, __LINE__, errors[clamped]); \
-        int *value = nullptr; \
+        int *volatile value = nullptr; \
         *value = 0; \
     }
 #else
```

2022-10-20 22:47 UTC, gzotti commented
Works on my oldest laptop, with Geforce 9800M GTX, Ubuntu 22.04.1. 
[log.txt](https://github.com/Stellarium/stellarium/files/9834389/log.txt)

For whatever reasons, building with Media support fails. Some egl functions cannot be found by the linker. Maybe I am just missing a package.   This is unrelated to the PR, though.

2022-10-21 00:40 UTC, gzotti commented
New test on my Intel i5-4570. Qt6.4, Core3.3 profile. Yes, works!
[log.txt](https://github.com/Stellarium/stellarium/files/9834753/log.txt)

There is still an GL_INVALID_OPERATION in the logfile.

2022-10-21 10:14 UTC, gzotti commented
Looks good (also with SMS) on 580M. 
[log_580M_3.3core_SMS.txt](https://github.com/Stellarium/stellarium/files/9838078/log_580M_3.3core_SMS.txt)

2022-10-21 10:24 UTC, 10110111 commented
> There is still an GL_INVALID_OPERATION in the logfile.

Does it happen in `master`?

2022-10-21 12:44 UTC, 10110111 commented
Invalid operation on Intel is now fixed (both in `master` and here). It was due to a mistake that was introduced at the very inception of `StelOpenGLArray` class, but was unnoticed due to zero VAO being a "default VAO" in Compatibility profile.

@alex-w I don't know whether it'll fix the error you see on macOS. If not, this will require some debugging, ideally using the patch for Qt that I posted above.

2022-10-21 15:00 UTC, alex-w commented
The error is gone

2022-10-21 21:22 UTC, 10110111 commented
OK, so this PR seems done now, including doc update. Is there any testing left to do, or shall I merge it?

2022-10-21 21:32 UTC, gzotti commented
I just wanted to test 960M and then startup my Intel 4570 one more time. And yes, I must test the Raspberries 3+4 for any change/break. Sorry, please don't merge yet.

2022-10-21 22:23 UTC, gzotti commented
Trying again to buils SMS on the Intel 4570. Your previous instructions were:

```
cmake -G "Visual Studio 16 2019" -DCMAKE_CXX_FLAGS="/ID:/StelDev/GIT/glm" -DCMAKE_PREFIX_PATH="D:/StelDev/GIT/eigen/share/eigen3/cmake" -DCMAKE_INSTALL_PREFIX=../CalcMySky_install ../CalcMySky -DQT_VERSION=6
cmake --build . --config Release
cmake --build . --config Release --target install
cp -rv ../CalcMySky/examples ../install/CalcMySky
```

I used the usual Windows command line here. 
The first `cmake --build` fails (see screenshots far above). The file `version_autogen.vcxproj` includes four lines with "true" statements. After deleting the lines, build succeeds with just the previous warnings (yellow lines in console.)

2022-10-21 22:33 UTC, 10110111 commented
Yup, broken `/bin/sh`, as we discussed at that point.

2022-10-21 22:36 UTC, gzotti commented
Found again on Raspberry 3 (see above, 12 days ago): 

GL_DOUBLE is `#define`d to GL_FLOAT in StelOpenGL.hpp. 
In StelPainter, please add this `#if` bracket. 

```
size_t StelPainter::ArrayDesc::vertexSizeInBytes() const
...
#if GL_DOUBLE != GL_FLOAT
	case GL_DOUBLE:
		elemSize = sizeof(GLdouble);
		break;
#endif

```

2022-10-21 22:58 UTC, gzotti commented
Now I have built SMS on my Intel i5-4570. Slow but pretty. 
[log_i5-4570_33core_OK.txt](https://github.com/Stellarium/stellarium/files/9842913/log_i5-4570_33core_OK.txt)

The compat mode still fails, though.
[log_i5-4570_compat_black.txt](https://github.com/Stellarium/stellarium/files/9842914/log_i5-4570_compat_black.txt)

This is probably not a blocker as long as the (now-default!) Core profile works reliably.

2022-10-21 23:08 UTC, 10110111 commented
> The compat mode still fails, though

Fails in what way? Only the errors that we see in the log, or some more noticeable problems?

2022-10-21 23:20 UTC, gzotti commented
Yes, black screen...

2022-10-21 23:22 UTC, 10110111 commented
Well, you can try running it via `apitrace` and see what triggers these errors. the `GL_INVALID_ENUM` is quite a puzzling one, especially when it appears in Compatibility profile but not in Core.

2022-10-21 23:23 UTC, gzotti commented
Raspi 3 is OK, just that it severely lacks texture memory. Is there a way to reduce the new button icons on loading for GLES systems (or with some other criterion?)? Maybe not this PR, but I think the pretty buttons waste memory here.

2022-10-21 23:25 UTC, 10110111 commented
> Is there a way to reduce the new button icons on loading for GLES systems (or with some other criterion?)?

Maybe. I feel all this will finally lead to a split of the graphics engine into two: one modern and the other for legacy/small systems.

2022-10-21 23:27 UTC, 10110111 commented
> it severely lacks texture memory

How did you diagnose it? `GL_OUT_OF_MEMORY` errors?

2022-10-21 23:36 UTC, gzotti commented
It behaves weird, program fails after a while, and dmesg messages indicates something that Google resolves to graphics memory issues. Earlier this happened with DSS or HiPS when zooming in, but now also when just loading more DSO images. Of course, also RPi is not free from error, but if it's just that little texture memory, we should just keep its use low on this platform. No DSS/HiPS or 3D sceneries is probably OK, and maybe some DSO images could also be reduced here.

2022-10-22 00:20 UTC, gzotti commented
RPi4 looks OK.
[log.txt](https://github.com/Stellarium/stellarium/files/9843130/log.txt)

2022-10-22 00:36 UTC, gzotti commented
I have no more objections. @alex-w ?

2022-10-22 06:04 UTC, alex-w approved these changes
ShowMySky works on macOS

@10110111 thank you for great work!

2022-10-22 09:38 UTC, closed without merging

2022-10-22 09:39 UTC, 10110111 commented
Well, GitHub, that was stupid.