Replace world map with a higher-resolution version
Stellarium/stellarium pull request #2742
Opened 2022-10-09 23:46 UTC by 10110111

### Description
The current world map in the _Location_ dialog has very poor resolution by today's standards: 500×250 pixels for the whole globe. This makes it useless to resize the _Location_ dialog to see the map closer.

This patch replaces the old map with a 5400×2700 version, taken from NASA [Blue Marble Next Generation dataset for July 2004](https://visibleearth.nasa.gov/images/74092/july-blue-marble-next-generation). As I understand, NASA imagery is in public domain, so copyright issues shouldn't arise.

The water here is marked with a darker color, but I think it's not critical.

### Screenshots

Old map:

![old](https://user-images.githubusercontent.com/6376882/194784944-1696f9cd-3260-440e-8632-1e380469c5e5.png)

New map:

![new](https://user-images.githubusercontent.com/6376882/194784949-a5c0e58e-be1b-40bd-bcb7-4457213bc6d2.png)

2022-10-09 23:52 UTC, alex-w requested changes
Please update section Graphics in CREDITS.md file

2022-10-10 00:30 UTC, alex-w approved these changes

2022-10-10 00:32 UTC, merged

2022-10-10 07:23 UTC, gzotti commented
While I agree on having a higher-res texture in principle, this will probably not work on systems with limited texture size. I have not tried yet, but OpenGL ES systems, esp. SBC like RPi3, may be limited to 2048x2048px (not sure about ANGLE). See my RPi3 remarks in #2729 : Probably even the larger button icons cause an issue by filling texture memory, so there is no more left for sky textures. I cannot say what the solution is, having some tool to reduce all textures after installation? Or adding code into the texture loader to reduce texture sizes on such systems?

2022-10-10 09:17 UTC, 10110111 commented
> this will probably not work on systems with limited texture size

`miscWorldMap.*` is only used via `QPixmap::scaled` and `QPainter`, so it shouldn't lead to any problems with texture size limit. Until we really find problems, it's just speculation.